/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing CostTariffs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CostTariffsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CostTariffs
        //private CostTariffs instance;

        public CostTariffsTests()
        {
            // TODO uncomment below to create an instance of CostTariffs
            //instance = new CostTariffs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CostTariffs
        /// </summary>
        [Fact]
        public void CostTariffsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CostTariffs
            //Assert.IsType<CostTariffs>(instance);
        }

        /// <summary>
        /// Test the property 'SetupCost'
        /// </summary>
        [Fact]
        public void SetupCostTest()
        {
            // TODO unit test for the property 'SetupCost'
        }

        /// <summary>
        /// Test the property 'CostPerMeter'
        /// </summary>
        [Fact]
        public void CostPerMeterTest()
        {
            // TODO unit test for the property 'CostPerMeter'
        }

        /// <summary>
        /// Test the property 'CostPerRotation'
        /// </summary>
        [Fact]
        public void CostPerRotationTest()
        {
            // TODO unit test for the property 'CostPerRotation'
        }

        /// <summary>
        /// Test the property 'CostPerStack'
        /// </summary>
        [Fact]
        public void CostPerStackTest()
        {
            // TODO unit test for the property 'CostPerStack'
        }

        /// <summary>
        /// Test the property 'CostPerCycle'
        /// </summary>
        [Fact]
        public void CostPerCycleTest()
        {
            // TODO unit test for the property 'CostPerCycle'
        }
    }
}
