/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing Cost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CostTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Cost
        //private Cost instance;

        public CostTests()
        {
            // TODO uncomment below to create an instance of Cost
            //instance = new Cost();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Cost
        /// </summary>
        [Fact]
        public void CostInstanceTest()
        {
            // TODO uncomment below to test "IsType" Cost
            //Assert.IsType<Cost>(instance);
        }

        /// <summary>
        /// Test the property 'SetupCost'
        /// </summary>
        [Fact]
        public void SetupCostTest()
        {
            // TODO unit test for the property 'SetupCost'
        }

        /// <summary>
        /// Test the property 'CuttingCost'
        /// </summary>
        [Fact]
        public void CuttingCostTest()
        {
            // TODO unit test for the property 'CuttingCost'
        }

        /// <summary>
        /// Test the property 'StackingCost'
        /// </summary>
        [Fact]
        public void StackingCostTest()
        {
            // TODO unit test for the property 'StackingCost'
        }

        /// <summary>
        /// Test the property 'RotationCost'
        /// </summary>
        [Fact]
        public void RotationCostTest()
        {
            // TODO unit test for the property 'RotationCost'
        }

        /// <summary>
        /// Test the property 'CycleCost'
        /// </summary>
        [Fact]
        public void CycleCostTest()
        {
            // TODO unit test for the property 'CycleCost'
        }

        /// <summary>
        /// Test the property 'TotalCost'
        /// </summary>
        [Fact]
        public void TotalCostTest()
        {
            // TODO unit test for the property 'TotalCost'
        }
    }
}
