/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing CutDirection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CutDirectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CutDirection
        //private CutDirection instance;

        public CutDirectionTests()
        {
            // TODO uncomment below to create an instance of CutDirection
            //instance = new CutDirection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CutDirection
        /// </summary>
        [Fact]
        public void CutDirectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CutDirection
            //Assert.IsType<CutDirection>(instance);
        }
    }
}
