/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing GrainDirection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GrainDirectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GrainDirection
        //private GrainDirection instance;

        public GrainDirectionTests()
        {
            // TODO uncomment below to create an instance of GrainDirection
            //instance = new GrainDirection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GrainDirection
        /// </summary>
        [Fact]
        public void GrainDirectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" GrainDirection
            //Assert.IsType<GrainDirection>(instance);
        }
    }
}
