/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing HealthResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HealthResponse
        //private HealthResponse instance;

        public HealthResponseTests()
        {
            // TODO uncomment below to create an instance of HealthResponse
            //instance = new HealthResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthResponse
        /// </summary>
        [Fact]
        public void HealthResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" HealthResponse
            //Assert.IsType<HealthResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
