/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing Layout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LayoutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Layout
        //private Layout instance;

        public LayoutTests()
        {
            // TODO uncomment below to create an instance of Layout
            //instance = new Layout();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Layout
        /// </summary>
        [Fact]
        public void LayoutInstanceTest()
        {
            // TODO uncomment below to test "IsType" Layout
            //Assert.IsType<Layout>(instance);
        }

        /// <summary>
        /// Test the property 'SheetId'
        /// </summary>
        [Fact]
        public void SheetIdTest()
        {
            // TODO unit test for the property 'SheetId'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Placements'
        /// </summary>
        [Fact]
        public void PlacementsTest()
        {
            // TODO unit test for the property 'Placements'
        }
    }
}
