/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing Machine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MachineTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Machine
        //private Machine instance;

        public MachineTests()
        {
            // TODO uncomment below to create an instance of Machine
            //instance = new Machine();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Machine
        /// </summary>
        [Fact]
        public void MachineInstanceTest()
        {
            // TODO uncomment below to test "IsType" Machine
            //Assert.IsType<Machine>(instance);
        }

        /// <summary>
        /// Test the property 'BladeThickness'
        /// </summary>
        [Fact]
        public void BladeThicknessTest()
        {
            // TODO unit test for the property 'BladeThickness'
        }

        /// <summary>
        /// Test the property 'MaxLevels'
        /// </summary>
        [Fact]
        public void MaxLevelsTest()
        {
            // TODO unit test for the property 'MaxLevels'
        }

        /// <summary>
        /// Test the property 'CutDirection'
        /// </summary>
        [Fact]
        public void CutDirectionTest()
        {
            // TODO unit test for the property 'CutDirection'
        }

        /// <summary>
        /// Test the property 'MaxStackHeight'
        /// </summary>
        [Fact]
        public void MaxStackHeightTest()
        {
            // TODO unit test for the property 'MaxStackHeight'
        }
    }
}
