/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing Margins
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MarginsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Margins
        //private Margins instance;

        public MarginsTests()
        {
            // TODO uncomment below to create an instance of Margins
            //instance = new Margins();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Margins
        /// </summary>
        [Fact]
        public void MarginsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Margins
            //Assert.IsType<Margins>(instance);
        }

        /// <summary>
        /// Test the property 'Top'
        /// </summary>
        [Fact]
        public void TopTest()
        {
            // TODO unit test for the property 'Top'
        }

        /// <summary>
        /// Test the property 'Bottom'
        /// </summary>
        [Fact]
        public void BottomTest()
        {
            // TODO unit test for the property 'Bottom'
        }

        /// <summary>
        /// Test the property 'Left'
        /// </summary>
        [Fact]
        public void LeftTest()
        {
            // TODO unit test for the property 'Left'
        }

        /// <summary>
        /// Test the property 'Right'
        /// </summary>
        [Fact]
        public void RightTest()
        {
            // TODO unit test for the property 'Right'
        }
    }
}
