/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing Metrics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetricsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Metrics
        //private Metrics instance;

        public MetricsTests()
        {
            // TODO uncomment below to create an instance of Metrics
            //instance = new Metrics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Metrics
        /// </summary>
        [Fact]
        public void MetricsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Metrics
            //Assert.IsType<Metrics>(instance);
        }

        /// <summary>
        /// Test the property 'TotalCutLength'
        /// </summary>
        [Fact]
        public void TotalCutLengthTest()
        {
            // TODO unit test for the property 'TotalCutLength'
        }

        /// <summary>
        /// Test the property 'TotalCuts'
        /// </summary>
        [Fact]
        public void TotalCutsTest()
        {
            // TODO unit test for the property 'TotalCuts'
        }

        /// <summary>
        /// Test the property 'TotalRotations'
        /// </summary>
        [Fact]
        public void TotalRotationsTest()
        {
            // TODO unit test for the property 'TotalRotations'
        }

        /// <summary>
        /// Test the property 'TotalStacks'
        /// </summary>
        [Fact]
        public void TotalStacksTest()
        {
            // TODO unit test for the property 'TotalStacks'
        }

        /// <summary>
        /// Test the property 'CutCycles'
        /// </summary>
        [Fact]
        public void CutCyclesTest()
        {
            // TODO unit test for the property 'CutCycles'
        }
    }
}
