/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing OptimizeResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OptimizeResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OptimizeResult
        //private OptimizeResult instance;

        public OptimizeResultTests()
        {
            // TODO uncomment below to create an instance of OptimizeResult
            //instance = new OptimizeResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OptimizeResult
        /// </summary>
        [Fact]
        public void OptimizeResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" OptimizeResult
            //Assert.IsType<OptimizeResult>(instance);
        }

        /// <summary>
        /// Test the property 'Layouts'
        /// </summary>
        [Fact]
        public void LayoutsTest()
        {
            // TODO unit test for the property 'Layouts'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Fact]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }

        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Fact]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }
    }
}
