/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing OptimizeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OptimizeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OptimizeRequest
        //private OptimizeRequest instance;

        public OptimizeRequestTests()
        {
            // TODO uncomment below to create an instance of OptimizeRequest
            //instance = new OptimizeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OptimizeRequest
        /// </summary>
        [Fact]
        public void OptimizeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OptimizeRequest
            //Assert.IsType<OptimizeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Parts'
        /// </summary>
        [Fact]
        public void PartsTest()
        {
            // TODO unit test for the property 'Parts'
        }

        /// <summary>
        /// Test the property 'Sheets'
        /// </summary>
        [Fact]
        public void SheetsTest()
        {
            // TODO unit test for the property 'Sheets'
        }

        /// <summary>
        /// Test the property 'Machine'
        /// </summary>
        [Fact]
        public void MachineTest()
        {
            // TODO unit test for the property 'Machine'
        }

        /// <summary>
        /// Test the property 'Strategy'
        /// </summary>
        [Fact]
        public void StrategyTest()
        {
            // TODO unit test for the property 'Strategy'
        }

        /// <summary>
        /// Test the property 'CostTariffs'
        /// </summary>
        [Fact]
        public void CostTariffsTest()
        {
            // TODO unit test for the property 'CostTariffs'
        }
    }
}
