/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing OptimizeAccepted
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OptimizeAcceptedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OptimizeAccepted
        //private OptimizeAccepted instance;

        public OptimizeAcceptedTests()
        {
            // TODO uncomment below to create an instance of OptimizeAccepted
            //instance = new OptimizeAccepted();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OptimizeAccepted
        /// </summary>
        [Fact]
        public void OptimizeAcceptedInstanceTest()
        {
            // TODO uncomment below to test "IsType" OptimizeAccepted
            //Assert.IsType<OptimizeAccepted>(instance);
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'PollUrl'
        /// </summary>
        [Fact]
        public void PollUrlTest()
        {
            // TODO unit test for the property 'PollUrl'
        }

        /// <summary>
        /// Test the property 'StreamUrl'
        /// </summary>
        [Fact]
        public void StreamUrlTest()
        {
            // TODO unit test for the property 'StreamUrl'
        }
    }
}
