/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing Part
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Part
        //private Part instance;

        public PartTests()
        {
            // TODO uncomment below to create an instance of Part
            //instance = new Part();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Part
        /// </summary>
        [Fact]
        public void PartInstanceTest()
        {
            // TODO uncomment below to test "IsType" Part
            //Assert.IsType<Part>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Grain'
        /// </summary>
        [Fact]
        public void GrainTest()
        {
            // TODO unit test for the property 'Grain'
        }

        /// <summary>
        /// Test the property 'EdgeBanding'
        /// </summary>
        [Fact]
        public void EdgeBandingTest()
        {
            // TODO unit test for the property 'EdgeBanding'
        }
    }
}
