/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing Placement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlacementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Placement
        //private Placement instance;

        public PlacementTests()
        {
            // TODO uncomment below to create an instance of Placement
            //instance = new Placement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Placement
        /// </summary>
        [Fact]
        public void PlacementInstanceTest()
        {
            // TODO uncomment below to test "IsType" Placement
            //Assert.IsType<Placement>(instance);
        }

        /// <summary>
        /// Test the property 'PartId'
        /// </summary>
        [Fact]
        public void PartIdTest()
        {
            // TODO unit test for the property 'PartId'
        }

        /// <summary>
        /// Test the property 'SheetId'
        /// </summary>
        [Fact]
        public void SheetIdTest()
        {
            // TODO unit test for the property 'SheetId'
        }

        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }

        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Fact]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Rotated'
        /// </summary>
        [Fact]
        public void RotatedTest()
        {
            // TODO unit test for the property 'Rotated'
        }

        /// <summary>
        /// Test the property 'Grain'
        /// </summary>
        [Fact]
        public void GrainTest()
        {
            // TODO unit test for the property 'Grain'
        }
    }
}
