/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing RateLimitError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RateLimitErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RateLimitError
        //private RateLimitError instance;

        public RateLimitErrorTests()
        {
            // TODO uncomment below to create an instance of RateLimitError
            //instance = new RateLimitError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RateLimitError
        /// </summary>
        [Fact]
        public void RateLimitErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" RateLimitError
            //Assert.IsType<RateLimitError>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'Remaining'
        /// </summary>
        [Fact]
        public void RemainingTest()
        {
            // TODO unit test for the property 'Remaining'
        }

        /// <summary>
        /// Test the property 'Strategy'
        /// </summary>
        [Fact]
        public void StrategyTest()
        {
            // TODO unit test for the property 'Strategy'
        }
    }
}
