/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing SheetUsage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SheetUsageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SheetUsage
        //private SheetUsage instance;

        public SheetUsageTests()
        {
            // TODO uncomment below to create an instance of SheetUsage
            //instance = new SheetUsage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SheetUsage
        /// </summary>
        [Fact]
        public void SheetUsageInstanceTest()
        {
            // TODO uncomment below to test "IsType" SheetUsage
            //Assert.IsType<SheetUsage>(instance);
        }

        /// <summary>
        /// Test the property 'SheetId'
        /// </summary>
        [Fact]
        public void SheetIdTest()
        {
            // TODO unit test for the property 'SheetId'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'YieldPercent'
        /// </summary>
        [Fact]
        public void YieldPercentTest()
        {
            // TODO unit test for the property 'YieldPercent'
        }

        /// <summary>
        /// Test the property 'ArticleNumber'
        /// </summary>
        [Fact]
        public void ArticleNumberTest()
        {
            // TODO unit test for the property 'ArticleNumber'
        }
    }
}
