/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing Summary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Summary
        //private Summary instance;

        public SummaryTests()
        {
            // TODO uncomment below to create an instance of Summary
            //instance = new Summary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Summary
        /// </summary>
        [Fact]
        public void SummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" Summary
            //Assert.IsType<Summary>(instance);
        }

        /// <summary>
        /// Test the property 'TotalSheets'
        /// </summary>
        [Fact]
        public void TotalSheetsTest()
        {
            // TODO unit test for the property 'TotalSheets'
        }

        /// <summary>
        /// Test the property 'YieldPercent'
        /// </summary>
        [Fact]
        public void YieldPercentTest()
        {
            // TODO unit test for the property 'YieldPercent'
        }

        /// <summary>
        /// Test the property 'WastePercent'
        /// </summary>
        [Fact]
        public void WastePercentTest()
        {
            // TODO unit test for the property 'WastePercent'
        }

        /// <summary>
        /// Test the property 'WasteArea'
        /// </summary>
        [Fact]
        public void WasteAreaTest()
        {
            // TODO unit test for the property 'WasteArea'
        }

        /// <summary>
        /// Test the property 'SheetsUsed'
        /// </summary>
        [Fact]
        public void SheetsUsedTest()
        {
            // TODO unit test for the property 'SheetsUsed'
        }

        /// <summary>
        /// Test the property 'UnplacedParts'
        /// </summary>
        [Fact]
        public void UnplacedPartsTest()
        {
            // TODO unit test for the property 'UnplacedParts'
        }
    }
}
