/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sawvant.Model;
using Sawvant.Client;
using System.Reflection;

namespace Sawvant.Test.Model
{
    /// <summary>
    ///  Class for testing TierDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TierDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TierDefinition
        //private TierDefinition instance;

        public TierDefinitionTests()
        {
            // TODO uncomment below to create an instance of TierDefinition
            //instance = new TierDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TierDefinition
        /// </summary>
        [Fact]
        public void TierDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" TierDefinition
            //Assert.IsType<TierDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'PriceEurCents'
        /// </summary>
        [Fact]
        public void PriceEurCentsTest()
        {
            // TODO unit test for the property 'PriceEurCents'
        }

        /// <summary>
        /// Test the property 'RateLimitFast'
        /// </summary>
        [Fact]
        public void RateLimitFastTest()
        {
            // TODO unit test for the property 'RateLimitFast'
        }

        /// <summary>
        /// Test the property 'RateLimitThorough'
        /// </summary>
        [Fact]
        public void RateLimitThoroughTest()
        {
            // TODO unit test for the property 'RateLimitThorough'
        }

        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }

        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
    }
}
