// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Cost
    /// </summary>
    public partial class Cost : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Cost" /> class.
        /// </summary>
        /// <param name="setupCost">setupCost</param>
        /// <param name="cuttingCost">cuttingCost</param>
        /// <param name="stackingCost">stackingCost</param>
        /// <param name="rotationCost">rotationCost</param>
        /// <param name="cycleCost">cycleCost</param>
        /// <param name="totalCost">totalCost</param>
        [JsonConstructor]
        public Cost(double setupCost, double cuttingCost, double stackingCost, double rotationCost, double cycleCost, double totalCost)
        {
            SetupCost = setupCost;
            CuttingCost = cuttingCost;
            StackingCost = stackingCost;
            RotationCost = rotationCost;
            CycleCost = cycleCost;
            TotalCost = totalCost;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SetupCost
        /// </summary>
        [JsonPropertyName("setup_cost")]
        public double SetupCost { get; set; }

        /// <summary>
        /// Gets or Sets CuttingCost
        /// </summary>
        [JsonPropertyName("cutting_cost")]
        public double CuttingCost { get; set; }

        /// <summary>
        /// Gets or Sets StackingCost
        /// </summary>
        [JsonPropertyName("stacking_cost")]
        public double StackingCost { get; set; }

        /// <summary>
        /// Gets or Sets RotationCost
        /// </summary>
        [JsonPropertyName("rotation_cost")]
        public double RotationCost { get; set; }

        /// <summary>
        /// Gets or Sets CycleCost
        /// </summary>
        [JsonPropertyName("cycle_cost")]
        public double CycleCost { get; set; }

        /// <summary>
        /// Gets or Sets TotalCost
        /// </summary>
        [JsonPropertyName("total_cost")]
        public double TotalCost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Cost {\n");
            sb.Append("  SetupCost: ").Append(SetupCost).Append("\n");
            sb.Append("  CuttingCost: ").Append(CuttingCost).Append("\n");
            sb.Append("  StackingCost: ").Append(StackingCost).Append("\n");
            sb.Append("  RotationCost: ").Append(RotationCost).Append("\n");
            sb.Append("  CycleCost: ").Append(CycleCost).Append("\n");
            sb.Append("  TotalCost: ").Append(TotalCost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Cost" />
    /// </summary>
    public class CostJsonConverter : JsonConverter<Cost>
    {
        /// <summary>
        /// Deserializes json to <see cref="Cost" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Cost Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> setupCost = default;
            Option<double?> cuttingCost = default;
            Option<double?> stackingCost = default;
            Option<double?> rotationCost = default;
            Option<double?> cycleCost = default;
            Option<double?> totalCost = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "setup_cost":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                setupCost = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "cutting_cost":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                cuttingCost = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "stacking_cost":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                stackingCost = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "rotation_cost":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                rotationCost = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "cycle_cost":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                cycleCost = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "total_cost":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                totalCost = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!setupCost.IsSet)
                throw new ArgumentException("Property is required for class Cost.", nameof(setupCost));

            if (!cuttingCost.IsSet)
                throw new ArgumentException("Property is required for class Cost.", nameof(cuttingCost));

            if (!stackingCost.IsSet)
                throw new ArgumentException("Property is required for class Cost.", nameof(stackingCost));

            if (!rotationCost.IsSet)
                throw new ArgumentException("Property is required for class Cost.", nameof(rotationCost));

            if (!cycleCost.IsSet)
                throw new ArgumentException("Property is required for class Cost.", nameof(cycleCost));

            if (!totalCost.IsSet)
                throw new ArgumentException("Property is required for class Cost.", nameof(totalCost));

            if (setupCost.IsSet && setupCost.Value == null)
                throw new ArgumentNullException(nameof(setupCost), "Property is not nullable for class Cost.");

            if (cuttingCost.IsSet && cuttingCost.Value == null)
                throw new ArgumentNullException(nameof(cuttingCost), "Property is not nullable for class Cost.");

            if (stackingCost.IsSet && stackingCost.Value == null)
                throw new ArgumentNullException(nameof(stackingCost), "Property is not nullable for class Cost.");

            if (rotationCost.IsSet && rotationCost.Value == null)
                throw new ArgumentNullException(nameof(rotationCost), "Property is not nullable for class Cost.");

            if (cycleCost.IsSet && cycleCost.Value == null)
                throw new ArgumentNullException(nameof(cycleCost), "Property is not nullable for class Cost.");

            if (totalCost.IsSet && totalCost.Value == null)
                throw new ArgumentNullException(nameof(totalCost), "Property is not nullable for class Cost.");

            return new Cost(setupCost.Value!.Value!, cuttingCost.Value!.Value!, stackingCost.Value!.Value!, rotationCost.Value!.Value!, cycleCost.Value!.Value!, totalCost.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Cost" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cost"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Cost cost, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, cost, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Cost" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cost"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Cost cost, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("setup_cost", cost.SetupCost);

            writer.WriteNumber("cutting_cost", cost.CuttingCost);

            writer.WriteNumber("stacking_cost", cost.StackingCost);

            writer.WriteNumber("rotation_cost", cost.RotationCost);

            writer.WriteNumber("cycle_cost", cost.CycleCost);

            writer.WriteNumber("total_cost", cost.TotalCost);
        }
    }
}
