// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// CostTariffs
    /// </summary>
    public partial class CostTariffs : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CostTariffs" /> class.
        /// </summary>
        /// <param name="setupCost">Fixed cost per job</param>
        /// <param name="costPerMeter">Cost per meter of cut length</param>
        /// <param name="costPerRotation">costPerRotation</param>
        /// <param name="costPerStack">costPerStack</param>
        /// <param name="costPerCycle">costPerCycle</param>
        [JsonConstructor]
        public CostTariffs(Option<double?> setupCost = default, Option<double?> costPerMeter = default, Option<double?> costPerRotation = default, Option<double?> costPerStack = default, Option<double?> costPerCycle = default)
        {
            SetupCostOption = setupCost;
            CostPerMeterOption = costPerMeter;
            CostPerRotationOption = costPerRotation;
            CostPerStackOption = costPerStack;
            CostPerCycleOption = costPerCycle;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SetupCost
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> SetupCostOption { get; private set; }

        /// <summary>
        /// Fixed cost per job
        /// </summary>
        /// <value>Fixed cost per job</value>
        [JsonPropertyName("setup_cost")]
        public double? SetupCost { get { return this.SetupCostOption; } set { this.SetupCostOption = new(value); } }

        /// <summary>
        /// Used to track the state of CostPerMeter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> CostPerMeterOption { get; private set; }

        /// <summary>
        /// Cost per meter of cut length
        /// </summary>
        /// <value>Cost per meter of cut length</value>
        [JsonPropertyName("cost_per_meter")]
        public double? CostPerMeter { get { return this.CostPerMeterOption; } set { this.CostPerMeterOption = new(value); } }

        /// <summary>
        /// Used to track the state of CostPerRotation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> CostPerRotationOption { get; private set; }

        /// <summary>
        /// Gets or Sets CostPerRotation
        /// </summary>
        [JsonPropertyName("cost_per_rotation")]
        public double? CostPerRotation { get { return this.CostPerRotationOption; } set { this.CostPerRotationOption = new(value); } }

        /// <summary>
        /// Used to track the state of CostPerStack
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> CostPerStackOption { get; private set; }

        /// <summary>
        /// Gets or Sets CostPerStack
        /// </summary>
        [JsonPropertyName("cost_per_stack")]
        public double? CostPerStack { get { return this.CostPerStackOption; } set { this.CostPerStackOption = new(value); } }

        /// <summary>
        /// Used to track the state of CostPerCycle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> CostPerCycleOption { get; private set; }

        /// <summary>
        /// Gets or Sets CostPerCycle
        /// </summary>
        [JsonPropertyName("cost_per_cycle")]
        public double? CostPerCycle { get { return this.CostPerCycleOption; } set { this.CostPerCycleOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CostTariffs {\n");
            sb.Append("  SetupCost: ").Append(SetupCost).Append("\n");
            sb.Append("  CostPerMeter: ").Append(CostPerMeter).Append("\n");
            sb.Append("  CostPerRotation: ").Append(CostPerRotation).Append("\n");
            sb.Append("  CostPerStack: ").Append(CostPerStack).Append("\n");
            sb.Append("  CostPerCycle: ").Append(CostPerCycle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CostTariffs" />
    /// </summary>
    public class CostTariffsJsonConverter : JsonConverter<CostTariffs>
    {
        /// <summary>
        /// Deserializes json to <see cref="CostTariffs" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CostTariffs Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> setupCost = default;
            Option<double?> costPerMeter = default;
            Option<double?> costPerRotation = default;
            Option<double?> costPerStack = default;
            Option<double?> costPerCycle = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "setup_cost":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                setupCost = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "cost_per_meter":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                costPerMeter = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "cost_per_rotation":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                costPerRotation = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "cost_per_stack":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                costPerStack = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "cost_per_cycle":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                costPerCycle = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (setupCost.IsSet && setupCost.Value == null)
                throw new ArgumentNullException(nameof(setupCost), "Property is not nullable for class CostTariffs.");

            if (costPerMeter.IsSet && costPerMeter.Value == null)
                throw new ArgumentNullException(nameof(costPerMeter), "Property is not nullable for class CostTariffs.");

            if (costPerRotation.IsSet && costPerRotation.Value == null)
                throw new ArgumentNullException(nameof(costPerRotation), "Property is not nullable for class CostTariffs.");

            if (costPerStack.IsSet && costPerStack.Value == null)
                throw new ArgumentNullException(nameof(costPerStack), "Property is not nullable for class CostTariffs.");

            if (costPerCycle.IsSet && costPerCycle.Value == null)
                throw new ArgumentNullException(nameof(costPerCycle), "Property is not nullable for class CostTariffs.");

            return new CostTariffs(setupCost, costPerMeter, costPerRotation, costPerStack, costPerCycle);
        }

        /// <summary>
        /// Serializes a <see cref="CostTariffs" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="costTariffs"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CostTariffs costTariffs, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, costTariffs, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CostTariffs" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="costTariffs"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CostTariffs costTariffs, JsonSerializerOptions jsonSerializerOptions)
        {
            if (costTariffs.SetupCostOption.IsSet)
                writer.WriteNumber("setup_cost", costTariffs.SetupCostOption.Value!.Value);

            if (costTariffs.CostPerMeterOption.IsSet)
                writer.WriteNumber("cost_per_meter", costTariffs.CostPerMeterOption.Value!.Value);

            if (costTariffs.CostPerRotationOption.IsSet)
                writer.WriteNumber("cost_per_rotation", costTariffs.CostPerRotationOption.Value!.Value);

            if (costTariffs.CostPerStackOption.IsSet)
                writer.WriteNumber("cost_per_stack", costTariffs.CostPerStackOption.Value!.Value);

            if (costTariffs.CostPerCycleOption.IsSet)
                writer.WriteNumber("cost_per_cycle", costTariffs.CostPerCycleOption.Value!.Value);
        }
    }
}
