// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Defines CutDirection
    /// </summary>
    public enum CutDirection
    {
        /// <summary>
        /// Enum Default for value: default
        /// </summary>
        Default = 1,

        /// <summary>
        /// Enum Rip for value: rip
        /// </summary>
        Rip = 2,

        /// <summary>
        /// Enum Cross for value: cross
        /// </summary>
        Cross = 3
    }

    /// <summary>
    /// Converts <see cref="CutDirection"/> to and from the JSON value
    /// </summary>
    public static class CutDirectionValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="CutDirection"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CutDirection FromString(string value)
        {
            if (value.Equals("default"))
                return CutDirection.Default;

            if (value.Equals("rip"))
                return CutDirection.Rip;

            if (value.Equals("cross"))
                return CutDirection.Cross;

            throw new NotImplementedException($"Could not convert value to type CutDirection: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="CutDirection"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CutDirection? FromStringOrDefault(string value)
        {
            if (value.Equals("default"))
                return CutDirection.Default;

            if (value.Equals("rip"))
                return CutDirection.Rip;

            if (value.Equals("cross"))
                return CutDirection.Cross;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CutDirection"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(CutDirection value)
        {
            if (value == CutDirection.Default)
                return "default";

            if (value == CutDirection.Rip)
                return "rip";

            if (value == CutDirection.Cross)
                return "cross";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CutDirection"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class CutDirectionJsonConverter : JsonConverter<CutDirection>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CutDirection Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            CutDirection? result = rawValue == null
                ? null
                : CutDirectionValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CutDirection to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cutDirection"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CutDirection cutDirection, JsonSerializerOptions options)
        {
            writer.WriteStringValue(cutDirection.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CutDirection"/>
    /// </summary>
    public class CutDirectionNullableJsonConverter : JsonConverter<CutDirection?>
    {
        /// <summary>
        /// Returns a CutDirection from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CutDirection? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            CutDirection? result = rawValue == null
                ? null
                : CutDirectionValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cutDirection"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CutDirection? cutDirection, JsonSerializerOptions options)
        {
            writer.WriteStringValue(cutDirection?.ToString() ?? "null");
        }
    }
}
