// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// EdgeCorrection
    /// </summary>
    public partial class EdgeCorrection : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeCorrection" /> class.
        /// </summary>
        /// <param name="top">mm added for edge banding (default to 0D)</param>
        /// <param name="bottom">bottom (default to 0D)</param>
        /// <param name="left">left (default to 0D)</param>
        /// <param name="right">right (default to 0D)</param>
        [JsonConstructor]
        public EdgeCorrection(Option<double?> top = default, Option<double?> bottom = default, Option<double?> left = default, Option<double?> right = default)
        {
            TopOption = top;
            BottomOption = bottom;
            LeftOption = left;
            RightOption = right;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Top
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> TopOption { get; private set; }

        /// <summary>
        /// mm added for edge banding
        /// </summary>
        /// <value>mm added for edge banding</value>
        [JsonPropertyName("top")]
        public double? Top { get { return this.TopOption; } set { this.TopOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bottom
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> BottomOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bottom
        /// </summary>
        [JsonPropertyName("bottom")]
        public double? Bottom { get { return this.BottomOption; } set { this.BottomOption = new(value); } }

        /// <summary>
        /// Used to track the state of Left
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> LeftOption { get; private set; }

        /// <summary>
        /// Gets or Sets Left
        /// </summary>
        [JsonPropertyName("left")]
        public double? Left { get { return this.LeftOption; } set { this.LeftOption = new(value); } }

        /// <summary>
        /// Used to track the state of Right
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> RightOption { get; private set; }

        /// <summary>
        /// Gets or Sets Right
        /// </summary>
        [JsonPropertyName("right")]
        public double? Right { get { return this.RightOption; } set { this.RightOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdgeCorrection {\n");
            sb.Append("  Top: ").Append(Top).Append("\n");
            sb.Append("  Bottom: ").Append(Bottom).Append("\n");
            sb.Append("  Left: ").Append(Left).Append("\n");
            sb.Append("  Right: ").Append(Right).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdgeCorrection" />
    /// </summary>
    public class EdgeCorrectionJsonConverter : JsonConverter<EdgeCorrection>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdgeCorrection" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdgeCorrection Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> top = default;
            Option<double?> bottom = default;
            Option<double?> left = default;
            Option<double?> right = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "top":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                top = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "bottom":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                bottom = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "left":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                left = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "right":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                right = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (top.IsSet && top.Value == null)
                throw new ArgumentNullException(nameof(top), "Property is not nullable for class EdgeCorrection.");

            if (bottom.IsSet && bottom.Value == null)
                throw new ArgumentNullException(nameof(bottom), "Property is not nullable for class EdgeCorrection.");

            if (left.IsSet && left.Value == null)
                throw new ArgumentNullException(nameof(left), "Property is not nullable for class EdgeCorrection.");

            if (right.IsSet && right.Value == null)
                throw new ArgumentNullException(nameof(right), "Property is not nullable for class EdgeCorrection.");

            return new EdgeCorrection(top, bottom, left, right);
        }

        /// <summary>
        /// Serializes a <see cref="EdgeCorrection" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edgeCorrection"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdgeCorrection edgeCorrection, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edgeCorrection, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdgeCorrection" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edgeCorrection"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdgeCorrection edgeCorrection, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edgeCorrection.TopOption.IsSet)
                writer.WriteNumber("top", edgeCorrection.TopOption.Value!.Value);

            if (edgeCorrection.BottomOption.IsSet)
                writer.WriteNumber("bottom", edgeCorrection.BottomOption.Value!.Value);

            if (edgeCorrection.LeftOption.IsSet)
                writer.WriteNumber("left", edgeCorrection.LeftOption.Value!.Value);

            if (edgeCorrection.RightOption.IsSet)
                writer.WriteNumber("right", edgeCorrection.RightOption.Value!.Value);
        }
    }
}
