// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Defines GrainDirection
    /// </summary>
    public enum GrainDirection
    {
        /// <summary>
        /// Enum None for value: none
        /// </summary>
        None = 1,

        /// <summary>
        /// Enum Length for value: length
        /// </summary>
        Length = 2,

        /// <summary>
        /// Enum Width for value: width
        /// </summary>
        Width = 3,

        /// <summary>
        /// Enum FreeSame for value: free_same
        /// </summary>
        FreeSame = 4
    }

    /// <summary>
    /// Converts <see cref="GrainDirection"/> to and from the JSON value
    /// </summary>
    public static class GrainDirectionValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="GrainDirection"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static GrainDirection FromString(string value)
        {
            if (value.Equals("none"))
                return GrainDirection.None;

            if (value.Equals("length"))
                return GrainDirection.Length;

            if (value.Equals("width"))
                return GrainDirection.Width;

            if (value.Equals("free_same"))
                return GrainDirection.FreeSame;

            throw new NotImplementedException($"Could not convert value to type GrainDirection: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="GrainDirection"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static GrainDirection? FromStringOrDefault(string value)
        {
            if (value.Equals("none"))
                return GrainDirection.None;

            if (value.Equals("length"))
                return GrainDirection.Length;

            if (value.Equals("width"))
                return GrainDirection.Width;

            if (value.Equals("free_same"))
                return GrainDirection.FreeSame;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="GrainDirection"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(GrainDirection value)
        {
            if (value == GrainDirection.None)
                return "none";

            if (value == GrainDirection.Length)
                return "length";

            if (value == GrainDirection.Width)
                return "width";

            if (value == GrainDirection.FreeSame)
                return "free_same";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GrainDirection"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class GrainDirectionJsonConverter : JsonConverter<GrainDirection>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override GrainDirection Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            GrainDirection? result = rawValue == null
                ? null
                : GrainDirectionValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the GrainDirection to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="grainDirection"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, GrainDirection grainDirection, JsonSerializerOptions options)
        {
            writer.WriteStringValue(grainDirection.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GrainDirection"/>
    /// </summary>
    public class GrainDirectionNullableJsonConverter : JsonConverter<GrainDirection?>
    {
        /// <summary>
        /// Returns a GrainDirection from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override GrainDirection? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            GrainDirection? result = rawValue == null
                ? null
                : GrainDirectionValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="grainDirection"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, GrainDirection? grainDirection, JsonSerializerOptions options)
        {
            writer.WriteStringValue(grainDirection?.ToString() ?? "null");
        }
    }
}
