// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// JobResponse
    /// </summary>
    public partial class JobResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobResponse" /> class.
        /// </summary>
        /// <param name="jobId">jobId</param>
        /// <param name="status">status</param>
        /// <param name="progress">progress</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="startedAt">startedAt</param>
        /// <param name="completedAt">completedAt</param>
        /// <param name="result">result</param>
        /// <param name="warnings">E.g. unplaced part IDs</param>
        /// <param name="error">error</param>
        [JsonConstructor]
        public JobResponse(Guid jobId, StatusEnum status, int progress, DateTime createdAt, Option<DateTime?> startedAt = default, Option<DateTime?> completedAt = default, Option<OptimizeResult?> result = default, Option<List<string>?> warnings = default, Option<string?> error = default)
        {
            JobId = jobId;
            Status = status;
            Progress = progress;
            CreatedAt = createdAt;
            StartedAtOption = startedAt;
            CompletedAtOption = completedAt;
            ResultOption = result;
            WarningsOption = warnings;
            ErrorOption = error;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 1,

            /// <summary>
            /// Enum Running for value: running
            /// </summary>
            Running = 2,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            Completed = 3,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 4
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("running"))
                return StatusEnum.Running;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("running"))
                return StatusEnum.Running;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Pending)
                return "pending";

            if (value == StatusEnum.Running)
                return "running";

            if (value == StatusEnum.Completed)
                return "completed";

            if (value == StatusEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [JsonPropertyName("job_id")]
        public Guid JobId { get; set; }

        /// <summary>
        /// Gets or Sets Progress
        /// </summary>
        [JsonPropertyName("progress")]
        public int Progress { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of StartedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StartedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets StartedAt
        /// </summary>
        [JsonPropertyName("started_at")]
        public DateTime? StartedAt { get { return this.StartedAtOption; } set { this.StartedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompletedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CompletedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [JsonPropertyName("completed_at")]
        public DateTime? CompletedAt { get { return this.CompletedAtOption; } set { this.CompletedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Result
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<OptimizeResult?> ResultOption { get; private set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [JsonPropertyName("result")]
        public OptimizeResult? Result { get { return this.ResultOption; } set { this.ResultOption = new(value); } }

        /// <summary>
        /// Used to track the state of Warnings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> WarningsOption { get; private set; }

        /// <summary>
        /// E.g. unplaced part IDs
        /// </summary>
        /// <value>E.g. unplaced part IDs</value>
        [JsonPropertyName("warnings")]
        public List<string>? Warnings { get { return this.WarningsOption; } set { this.WarningsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Error
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public string? Error { get { return this.ErrorOption; } set { this.ErrorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobResponse {\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Progress: ").Append(Progress).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Progress (int) maximum
            if (this.Progress > (int)100)
            {
                yield return new ValidationResult("Invalid value for Progress, must be a value less than or equal to 100.", new [] { "Progress" });
            }

            // Progress (int) minimum
            if (this.Progress < (int)0)
            {
                yield return new ValidationResult("Invalid value for Progress, must be a value greater than or equal to 0.", new [] { "Progress" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobResponse" />
    /// </summary>
    public class JobResponseJsonConverter : JsonConverter<JobResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize StartedAt
        /// </summary>
        public static string StartedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedAt
        /// </summary>
        public static string CompletedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="JobResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> jobId = default;
            Option<JobResponse.StatusEnum?> status = default;
            Option<int?> progress = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> startedAt = default;
            Option<DateTime?> completedAt = default;
            Option<OptimizeResult?> result = default;
            Option<List<string>?> warnings = default;
            Option<string?> error = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "job_id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                jobId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<JobResponse.StatusEnum?>(JobResponse.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "progress":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                progress = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "created_at":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "started_at":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                startedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "completed_at":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                completedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "result":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                result = new Option<OptimizeResult?>(JsonSerializer.Deserialize<OptimizeResult>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "warnings":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                warnings = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "error":
                            error = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!jobId.IsSet)
                throw new ArgumentException("Property is required for class JobResponse.", nameof(jobId));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class JobResponse.", nameof(status));

            if (!progress.IsSet)
                throw new ArgumentException("Property is required for class JobResponse.", nameof(progress));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class JobResponse.", nameof(createdAt));

            if (jobId.IsSet && jobId.Value == null)
                throw new ArgumentNullException(nameof(jobId), "Property is not nullable for class JobResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class JobResponse.");

            if (progress.IsSet && progress.Value == null)
                throw new ArgumentNullException(nameof(progress), "Property is not nullable for class JobResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class JobResponse.");

            if (startedAt.IsSet && startedAt.Value == null)
                throw new ArgumentNullException(nameof(startedAt), "Property is not nullable for class JobResponse.");

            if (completedAt.IsSet && completedAt.Value == null)
                throw new ArgumentNullException(nameof(completedAt), "Property is not nullable for class JobResponse.");

            if (result.IsSet && result.Value == null)
                throw new ArgumentNullException(nameof(result), "Property is not nullable for class JobResponse.");

            if (warnings.IsSet && warnings.Value == null)
                throw new ArgumentNullException(nameof(warnings), "Property is not nullable for class JobResponse.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class JobResponse.");

            return new JobResponse(jobId.Value!.Value!, status.Value!.Value!, progress.Value!.Value!, createdAt.Value!.Value!, startedAt, completedAt, result, warnings, error);
        }

        /// <summary>
        /// Serializes a <see cref="JobResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobResponse jobResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobResponse jobResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (jobResponse.ResultOption.IsSet && jobResponse.Result == null)
                throw new ArgumentNullException(nameof(jobResponse.Result), "Property is required for class JobResponse.");

            if (jobResponse.WarningsOption.IsSet && jobResponse.Warnings == null)
                throw new ArgumentNullException(nameof(jobResponse.Warnings), "Property is required for class JobResponse.");

            if (jobResponse.ErrorOption.IsSet && jobResponse.Error == null)
                throw new ArgumentNullException(nameof(jobResponse.Error), "Property is required for class JobResponse.");

            writer.WriteString("job_id", jobResponse.JobId);

            var statusRawValue = JobResponse.StatusEnumToJsonValue(jobResponse.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteNumber("progress", jobResponse.Progress);

            writer.WriteString("created_at", jobResponse.CreatedAt.ToString(CreatedAtFormat));

            if (jobResponse.StartedAtOption.IsSet)
                writer.WriteString("started_at", jobResponse.StartedAtOption.Value!.Value.ToString(StartedAtFormat));

            if (jobResponse.CompletedAtOption.IsSet)
                writer.WriteString("completed_at", jobResponse.CompletedAtOption.Value!.Value.ToString(CompletedAtFormat));

            if (jobResponse.ResultOption.IsSet)
            {
                writer.WritePropertyName("result");
                JsonSerializer.Serialize(writer, jobResponse.Result, jsonSerializerOptions);
            }
            if (jobResponse.WarningsOption.IsSet)
            {
                writer.WritePropertyName("warnings");
                JsonSerializer.Serialize(writer, jobResponse.Warnings, jsonSerializerOptions);
            }
            if (jobResponse.ErrorOption.IsSet)
                writer.WriteString("error", jobResponse.Error);
        }
    }
}
