// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Layout
    /// </summary>
    public partial class Layout : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Layout" /> class.
        /// </summary>
        /// <param name="sheetId">sheetId</param>
        /// <param name="quantity">Number of identical sheets using this layout pattern</param>
        /// <param name="placements">placements</param>
        [JsonConstructor]
        public Layout(string sheetId, int quantity, List<Placement> placements)
        {
            SheetId = sheetId;
            Quantity = quantity;
            Placements = placements;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SheetId
        /// </summary>
        [JsonPropertyName("sheet_id")]
        public string SheetId { get; set; }

        /// <summary>
        /// Number of identical sheets using this layout pattern
        /// </summary>
        /// <value>Number of identical sheets using this layout pattern</value>
        [JsonPropertyName("quantity")]
        public int Quantity { get; set; }

        /// <summary>
        /// Gets or Sets Placements
        /// </summary>
        [JsonPropertyName("placements")]
        public List<Placement> Placements { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Layout {\n");
            sb.Append("  SheetId: ").Append(SheetId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Placements: ").Append(Placements).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Layout" />
    /// </summary>
    public class LayoutJsonConverter : JsonConverter<Layout>
    {
        /// <summary>
        /// Deserializes json to <see cref="Layout" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Layout Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> sheetId = default;
            Option<int?> quantity = default;
            Option<List<Placement>?> placements = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sheet_id":
                            sheetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "quantity":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                quantity = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "placements":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                placements = new Option<List<Placement>?>(JsonSerializer.Deserialize<List<Placement>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!sheetId.IsSet)
                throw new ArgumentException("Property is required for class Layout.", nameof(sheetId));

            if (!quantity.IsSet)
                throw new ArgumentException("Property is required for class Layout.", nameof(quantity));

            if (!placements.IsSet)
                throw new ArgumentException("Property is required for class Layout.", nameof(placements));

            if (sheetId.IsSet && sheetId.Value == null)
                throw new ArgumentNullException(nameof(sheetId), "Property is not nullable for class Layout.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class Layout.");

            if (placements.IsSet && placements.Value == null)
                throw new ArgumentNullException(nameof(placements), "Property is not nullable for class Layout.");

            return new Layout(sheetId.Value!, quantity.Value!.Value!, placements.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Layout" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="layout"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Layout layout, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, layout, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Layout" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="layout"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Layout layout, JsonSerializerOptions jsonSerializerOptions)
        {
            if (layout.SheetId == null)
                throw new ArgumentNullException(nameof(layout.SheetId), "Property is required for class Layout.");

            if (layout.Placements == null)
                throw new ArgumentNullException(nameof(layout.Placements), "Property is required for class Layout.");

            writer.WriteString("sheet_id", layout.SheetId);

            writer.WriteNumber("quantity", layout.Quantity);

            writer.WritePropertyName("placements");
            JsonSerializer.Serialize(writer, layout.Placements, jsonSerializerOptions);
        }
    }
}
