// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Machine
    /// </summary>
    public partial class Machine : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Machine" /> class.
        /// </summary>
        /// <param name="bladeThickness">Kerf width in mm</param>
        /// <param name="maxLevels">Cut pattern complexity (1-3)</param>
        /// <param name="cutDirection">cutDirection</param>
        /// <param name="maxStackHeight">Maximum stack height in mm for batch cutting</param>
        [JsonConstructor]
        public Machine(double bladeThickness, int maxLevels, CutDirection cutDirection, Option<double?> maxStackHeight = default)
        {
            BladeThickness = bladeThickness;
            MaxLevels = maxLevels;
            CutDirection = cutDirection;
            MaxStackHeightOption = maxStackHeight;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CutDirection
        /// </summary>
        [JsonPropertyName("cut_direction")]
        public CutDirection CutDirection { get; set; }

        /// <summary>
        /// Kerf width in mm
        /// </summary>
        /// <value>Kerf width in mm</value>
        [JsonPropertyName("blade_thickness")]
        public double BladeThickness { get; set; }

        /// <summary>
        /// Cut pattern complexity (1-3)
        /// </summary>
        /// <value>Cut pattern complexity (1-3)</value>
        [JsonPropertyName("max_levels")]
        public int MaxLevels { get; set; }

        /// <summary>
        /// Used to track the state of MaxStackHeight
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> MaxStackHeightOption { get; private set; }

        /// <summary>
        /// Maximum stack height in mm for batch cutting
        /// </summary>
        /// <value>Maximum stack height in mm for batch cutting</value>
        [JsonPropertyName("max_stack_height")]
        public double? MaxStackHeight { get { return this.MaxStackHeightOption; } set { this.MaxStackHeightOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Machine {\n");
            sb.Append("  BladeThickness: ").Append(BladeThickness).Append("\n");
            sb.Append("  MaxLevels: ").Append(MaxLevels).Append("\n");
            sb.Append("  CutDirection: ").Append(CutDirection).Append("\n");
            sb.Append("  MaxStackHeight: ").Append(MaxStackHeight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MaxLevels (int) maximum
            if (this.MaxLevels > (int)3)
            {
                yield return new ValidationResult("Invalid value for MaxLevels, must be a value less than or equal to 3.", new [] { "MaxLevels" });
            }

            // MaxLevels (int) minimum
            if (this.MaxLevels < (int)1)
            {
                yield return new ValidationResult("Invalid value for MaxLevels, must be a value greater than or equal to 1.", new [] { "MaxLevels" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Machine" />
    /// </summary>
    public class MachineJsonConverter : JsonConverter<Machine>
    {
        /// <summary>
        /// Deserializes json to <see cref="Machine" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Machine Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> bladeThickness = default;
            Option<int?> maxLevels = default;
            Option<CutDirection?> cutDirection = default;
            Option<double?> maxStackHeight = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "blade_thickness":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                bladeThickness = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "max_levels":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                maxLevels = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "cut_direction":
                            string? cutDirectionRawValue = utf8JsonReader.GetString();
                            if (cutDirectionRawValue != null)
                                cutDirection = new Option<CutDirection?>(CutDirectionValueConverter.FromStringOrDefault(cutDirectionRawValue));
                            break;
                        case "max_stack_height":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                maxStackHeight = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!bladeThickness.IsSet)
                throw new ArgumentException("Property is required for class Machine.", nameof(bladeThickness));

            if (!maxLevels.IsSet)
                throw new ArgumentException("Property is required for class Machine.", nameof(maxLevels));

            if (!cutDirection.IsSet)
                throw new ArgumentException("Property is required for class Machine.", nameof(cutDirection));

            if (bladeThickness.IsSet && bladeThickness.Value == null)
                throw new ArgumentNullException(nameof(bladeThickness), "Property is not nullable for class Machine.");

            if (maxLevels.IsSet && maxLevels.Value == null)
                throw new ArgumentNullException(nameof(maxLevels), "Property is not nullable for class Machine.");

            if (cutDirection.IsSet && cutDirection.Value == null)
                throw new ArgumentNullException(nameof(cutDirection), "Property is not nullable for class Machine.");

            if (maxStackHeight.IsSet && maxStackHeight.Value == null)
                throw new ArgumentNullException(nameof(maxStackHeight), "Property is not nullable for class Machine.");

            return new Machine(bladeThickness.Value!.Value!, maxLevels.Value!.Value!, cutDirection.Value!.Value!, maxStackHeight);
        }

        /// <summary>
        /// Serializes a <see cref="Machine" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="machine"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Machine machine, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, machine, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Machine" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="machine"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Machine machine, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("blade_thickness", machine.BladeThickness);

            writer.WriteNumber("max_levels", machine.MaxLevels);

            var cutDirectionRawValue = CutDirectionValueConverter.ToJsonValue(machine.CutDirection);
            writer.WriteString("cut_direction", cutDirectionRawValue);

            if (machine.MaxStackHeightOption.IsSet)
                writer.WriteNumber("max_stack_height", machine.MaxStackHeightOption.Value!.Value);
        }
    }
}
