// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Metrics
    /// </summary>
    public partial class Metrics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Metrics" /> class.
        /// </summary>
        /// <param name="totalCutLength">Total cut length in mm</param>
        /// <param name="totalCuts">totalCuts</param>
        /// <param name="totalRotations">totalRotations</param>
        /// <param name="totalStacks">totalStacks</param>
        /// <param name="cutCycles">cutCycles</param>
        [JsonConstructor]
        public Metrics(double totalCutLength, int totalCuts, int totalRotations, int totalStacks, int cutCycles)
        {
            TotalCutLength = totalCutLength;
            TotalCuts = totalCuts;
            TotalRotations = totalRotations;
            TotalStacks = totalStacks;
            CutCycles = cutCycles;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Total cut length in mm
        /// </summary>
        /// <value>Total cut length in mm</value>
        [JsonPropertyName("total_cut_length")]
        public double TotalCutLength { get; set; }

        /// <summary>
        /// Gets or Sets TotalCuts
        /// </summary>
        [JsonPropertyName("total_cuts")]
        public int TotalCuts { get; set; }

        /// <summary>
        /// Gets or Sets TotalRotations
        /// </summary>
        [JsonPropertyName("total_rotations")]
        public int TotalRotations { get; set; }

        /// <summary>
        /// Gets or Sets TotalStacks
        /// </summary>
        [JsonPropertyName("total_stacks")]
        public int TotalStacks { get; set; }

        /// <summary>
        /// Gets or Sets CutCycles
        /// </summary>
        [JsonPropertyName("cut_cycles")]
        public int CutCycles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Metrics {\n");
            sb.Append("  TotalCutLength: ").Append(TotalCutLength).Append("\n");
            sb.Append("  TotalCuts: ").Append(TotalCuts).Append("\n");
            sb.Append("  TotalRotations: ").Append(TotalRotations).Append("\n");
            sb.Append("  TotalStacks: ").Append(TotalStacks).Append("\n");
            sb.Append("  CutCycles: ").Append(CutCycles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Metrics" />
    /// </summary>
    public class MetricsJsonConverter : JsonConverter<Metrics>
    {
        /// <summary>
        /// Deserializes json to <see cref="Metrics" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Metrics Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> totalCutLength = default;
            Option<int?> totalCuts = default;
            Option<int?> totalRotations = default;
            Option<int?> totalStacks = default;
            Option<int?> cutCycles = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "total_cut_length":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                totalCutLength = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "total_cuts":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                totalCuts = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "total_rotations":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                totalRotations = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "total_stacks":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                totalStacks = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "cut_cycles":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                cutCycles = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!totalCutLength.IsSet)
                throw new ArgumentException("Property is required for class Metrics.", nameof(totalCutLength));

            if (!totalCuts.IsSet)
                throw new ArgumentException("Property is required for class Metrics.", nameof(totalCuts));

            if (!totalRotations.IsSet)
                throw new ArgumentException("Property is required for class Metrics.", nameof(totalRotations));

            if (!totalStacks.IsSet)
                throw new ArgumentException("Property is required for class Metrics.", nameof(totalStacks));

            if (!cutCycles.IsSet)
                throw new ArgumentException("Property is required for class Metrics.", nameof(cutCycles));

            if (totalCutLength.IsSet && totalCutLength.Value == null)
                throw new ArgumentNullException(nameof(totalCutLength), "Property is not nullable for class Metrics.");

            if (totalCuts.IsSet && totalCuts.Value == null)
                throw new ArgumentNullException(nameof(totalCuts), "Property is not nullable for class Metrics.");

            if (totalRotations.IsSet && totalRotations.Value == null)
                throw new ArgumentNullException(nameof(totalRotations), "Property is not nullable for class Metrics.");

            if (totalStacks.IsSet && totalStacks.Value == null)
                throw new ArgumentNullException(nameof(totalStacks), "Property is not nullable for class Metrics.");

            if (cutCycles.IsSet && cutCycles.Value == null)
                throw new ArgumentNullException(nameof(cutCycles), "Property is not nullable for class Metrics.");

            return new Metrics(totalCutLength.Value!.Value!, totalCuts.Value!.Value!, totalRotations.Value!.Value!, totalStacks.Value!.Value!, cutCycles.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Metrics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metrics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Metrics metrics, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, metrics, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Metrics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metrics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Metrics metrics, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("total_cut_length", metrics.TotalCutLength);

            writer.WriteNumber("total_cuts", metrics.TotalCuts);

            writer.WriteNumber("total_rotations", metrics.TotalRotations);

            writer.WriteNumber("total_stacks", metrics.TotalStacks);

            writer.WriteNumber("cut_cycles", metrics.CutCycles);
        }
    }
}
