// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// OptimizeResult
    /// </summary>
    public partial class OptimizeResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OptimizeResult" /> class.
        /// </summary>
        /// <param name="layouts">layouts</param>
        /// <param name="summary">summary</param>
        /// <param name="metrics">metrics</param>
        /// <param name="cost">cost</param>
        [JsonConstructor]
        public OptimizeResult(List<Layout> layouts, Summary summary, Option<Metrics?> metrics = default, Option<Cost?> cost = default)
        {
            Layouts = layouts;
            Summary = summary;
            MetricsOption = metrics;
            CostOption = cost;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Layouts
        /// </summary>
        [JsonPropertyName("layouts")]
        public List<Layout> Layouts { get; set; }

        /// <summary>
        /// Gets or Sets Summary
        /// </summary>
        [JsonPropertyName("summary")]
        public Summary Summary { get; set; }

        /// <summary>
        /// Used to track the state of Metrics
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Metrics?> MetricsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Metrics
        /// </summary>
        [JsonPropertyName("metrics")]
        public Metrics? Metrics { get { return this.MetricsOption; } set { this.MetricsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cost
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Cost?> CostOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cost
        /// </summary>
        [JsonPropertyName("cost")]
        public Cost? Cost { get { return this.CostOption; } set { this.CostOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OptimizeResult {\n");
            sb.Append("  Layouts: ").Append(Layouts).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  Metrics: ").Append(Metrics).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OptimizeResult" />
    /// </summary>
    public class OptimizeResultJsonConverter : JsonConverter<OptimizeResult>
    {
        /// <summary>
        /// Deserializes json to <see cref="OptimizeResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OptimizeResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<Layout>?> layouts = default;
            Option<Summary?> summary = default;
            Option<Metrics?> metrics = default;
            Option<Cost?> cost = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "layouts":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                layouts = new Option<List<Layout>?>(JsonSerializer.Deserialize<List<Layout>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "summary":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                summary = new Option<Summary?>(JsonSerializer.Deserialize<Summary>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "metrics":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                metrics = new Option<Metrics?>(JsonSerializer.Deserialize<Metrics>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "cost":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                cost = new Option<Cost?>(JsonSerializer.Deserialize<Cost>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!layouts.IsSet)
                throw new ArgumentException("Property is required for class OptimizeResult.", nameof(layouts));

            if (!summary.IsSet)
                throw new ArgumentException("Property is required for class OptimizeResult.", nameof(summary));

            if (layouts.IsSet && layouts.Value == null)
                throw new ArgumentNullException(nameof(layouts), "Property is not nullable for class OptimizeResult.");

            if (summary.IsSet && summary.Value == null)
                throw new ArgumentNullException(nameof(summary), "Property is not nullable for class OptimizeResult.");

            if (metrics.IsSet && metrics.Value == null)
                throw new ArgumentNullException(nameof(metrics), "Property is not nullable for class OptimizeResult.");

            if (cost.IsSet && cost.Value == null)
                throw new ArgumentNullException(nameof(cost), "Property is not nullable for class OptimizeResult.");

            return new OptimizeResult(layouts.Value!, summary.Value!, metrics, cost);
        }

        /// <summary>
        /// Serializes a <see cref="OptimizeResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="optimizeResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OptimizeResult optimizeResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, optimizeResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OptimizeResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="optimizeResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OptimizeResult optimizeResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (optimizeResult.Layouts == null)
                throw new ArgumentNullException(nameof(optimizeResult.Layouts), "Property is required for class OptimizeResult.");

            if (optimizeResult.Summary == null)
                throw new ArgumentNullException(nameof(optimizeResult.Summary), "Property is required for class OptimizeResult.");

            if (optimizeResult.MetricsOption.IsSet && optimizeResult.Metrics == null)
                throw new ArgumentNullException(nameof(optimizeResult.Metrics), "Property is required for class OptimizeResult.");

            if (optimizeResult.CostOption.IsSet && optimizeResult.Cost == null)
                throw new ArgumentNullException(nameof(optimizeResult.Cost), "Property is required for class OptimizeResult.");

            writer.WritePropertyName("layouts");
            JsonSerializer.Serialize(writer, optimizeResult.Layouts, jsonSerializerOptions);
            writer.WritePropertyName("summary");
            JsonSerializer.Serialize(writer, optimizeResult.Summary, jsonSerializerOptions);
            if (optimizeResult.MetricsOption.IsSet)
            {
                writer.WritePropertyName("metrics");
                JsonSerializer.Serialize(writer, optimizeResult.Metrics, jsonSerializerOptions);
            }
            if (optimizeResult.CostOption.IsSet)
            {
                writer.WritePropertyName("cost");
                JsonSerializer.Serialize(writer, optimizeResult.Cost, jsonSerializerOptions);
            }
        }
    }
}
