// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// OptimizeRequest
    /// </summary>
    public partial class OptimizeRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OptimizeRequest" /> class.
        /// </summary>
        /// <param name="parts">parts</param>
        /// <param name="sheets">sheets</param>
        /// <param name="machine">machine</param>
        /// <param name="strategy">Solve strategy. \&quot;fast\&quot; runs all greedy solvers concurrently. \&quot;thorough\&quot; adds Gilmore-Gomory column generation for optimal patterns. Each strategy has its own rate limit quota.  (default to StrategyEnum.Fast)</param>
        /// <param name="costTariffs">costTariffs</param>
        [JsonConstructor]
        public OptimizeRequest(List<Part> parts, List<Sheet> sheets, Machine machine, Option<StrategyEnum?> strategy = default, Option<CostTariffs?> costTariffs = default)
        {
            Parts = parts;
            Sheets = sheets;
            Machine = machine;
            StrategyOption = strategy;
            CostTariffsOption = costTariffs;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Solve strategy. \&quot;fast\&quot; runs all greedy solvers concurrently. \&quot;thorough\&quot; adds Gilmore-Gomory column generation for optimal patterns. Each strategy has its own rate limit quota. 
        /// </summary>
        /// <value>Solve strategy. \&quot;fast\&quot; runs all greedy solvers concurrently. \&quot;thorough\&quot; adds Gilmore-Gomory column generation for optimal patterns. Each strategy has its own rate limit quota. </value>
        public enum StrategyEnum
        {
            /// <summary>
            /// Enum Fast for value: fast
            /// </summary>
            Fast = 1,

            /// <summary>
            /// Enum Thorough for value: thorough
            /// </summary>
            Thorough = 2
        }

        /// <summary>
        /// Returns a <see cref="StrategyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StrategyEnum StrategyEnumFromString(string value)
        {
            if (value.Equals("fast"))
                return StrategyEnum.Fast;

            if (value.Equals("thorough"))
                return StrategyEnum.Thorough;

            throw new NotImplementedException($"Could not convert value to type StrategyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StrategyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StrategyEnum? StrategyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("fast"))
                return StrategyEnum.Fast;

            if (value.Equals("thorough"))
                return StrategyEnum.Thorough;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StrategyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StrategyEnumToJsonValue(StrategyEnum? value)
        {
            if (value == StrategyEnum.Fast)
                return "fast";

            if (value == StrategyEnum.Thorough)
                return "thorough";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Strategy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StrategyEnum?> StrategyOption { get; private set; }

        /// <summary>
        /// Solve strategy. \&quot;fast\&quot; runs all greedy solvers concurrently. \&quot;thorough\&quot; adds Gilmore-Gomory column generation for optimal patterns. Each strategy has its own rate limit quota. 
        /// </summary>
        /// <value>Solve strategy. \&quot;fast\&quot; runs all greedy solvers concurrently. \&quot;thorough\&quot; adds Gilmore-Gomory column generation for optimal patterns. Each strategy has its own rate limit quota. </value>
        [JsonPropertyName("strategy")]
        public StrategyEnum? Strategy { get { return this.StrategyOption; } set { this.StrategyOption = new(value); } }

        /// <summary>
        /// Gets or Sets Parts
        /// </summary>
        [JsonPropertyName("parts")]
        public List<Part> Parts { get; set; }

        /// <summary>
        /// Gets or Sets Sheets
        /// </summary>
        [JsonPropertyName("sheets")]
        public List<Sheet> Sheets { get; set; }

        /// <summary>
        /// Gets or Sets Machine
        /// </summary>
        [JsonPropertyName("machine")]
        public Machine Machine { get; set; }

        /// <summary>
        /// Used to track the state of CostTariffs
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CostTariffs?> CostTariffsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CostTariffs
        /// </summary>
        [JsonPropertyName("cost_tariffs")]
        public CostTariffs? CostTariffs { get { return this.CostTariffsOption; } set { this.CostTariffsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OptimizeRequest {\n");
            sb.Append("  Parts: ").Append(Parts).Append("\n");
            sb.Append("  Sheets: ").Append(Sheets).Append("\n");
            sb.Append("  Machine: ").Append(Machine).Append("\n");
            sb.Append("  Strategy: ").Append(Strategy).Append("\n");
            sb.Append("  CostTariffs: ").Append(CostTariffs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OptimizeRequest" />
    /// </summary>
    public class OptimizeRequestJsonConverter : JsonConverter<OptimizeRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="OptimizeRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OptimizeRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<Part>?> parts = default;
            Option<List<Sheet>?> sheets = default;
            Option<Machine?> machine = default;
            Option<OptimizeRequest.StrategyEnum?> strategy = default;
            Option<CostTariffs?> costTariffs = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "parts":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                parts = new Option<List<Part>?>(JsonSerializer.Deserialize<List<Part>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "sheets":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                sheets = new Option<List<Sheet>?>(JsonSerializer.Deserialize<List<Sheet>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "machine":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                machine = new Option<Machine?>(JsonSerializer.Deserialize<Machine>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "strategy":
                            string? strategyRawValue = utf8JsonReader.GetString();
                            if (strategyRawValue != null)
                                strategy = new Option<OptimizeRequest.StrategyEnum?>(OptimizeRequest.StrategyEnumFromStringOrDefault(strategyRawValue));
                            break;
                        case "cost_tariffs":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                costTariffs = new Option<CostTariffs?>(JsonSerializer.Deserialize<CostTariffs>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!parts.IsSet)
                throw new ArgumentException("Property is required for class OptimizeRequest.", nameof(parts));

            if (!sheets.IsSet)
                throw new ArgumentException("Property is required for class OptimizeRequest.", nameof(sheets));

            if (!machine.IsSet)
                throw new ArgumentException("Property is required for class OptimizeRequest.", nameof(machine));

            if (parts.IsSet && parts.Value == null)
                throw new ArgumentNullException(nameof(parts), "Property is not nullable for class OptimizeRequest.");

            if (sheets.IsSet && sheets.Value == null)
                throw new ArgumentNullException(nameof(sheets), "Property is not nullable for class OptimizeRequest.");

            if (machine.IsSet && machine.Value == null)
                throw new ArgumentNullException(nameof(machine), "Property is not nullable for class OptimizeRequest.");

            if (strategy.IsSet && strategy.Value == null)
                throw new ArgumentNullException(nameof(strategy), "Property is not nullable for class OptimizeRequest.");

            if (costTariffs.IsSet && costTariffs.Value == null)
                throw new ArgumentNullException(nameof(costTariffs), "Property is not nullable for class OptimizeRequest.");

            return new OptimizeRequest(parts.Value!, sheets.Value!, machine.Value!, strategy, costTariffs);
        }

        /// <summary>
        /// Serializes a <see cref="OptimizeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="optimizeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OptimizeRequest optimizeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, optimizeRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OptimizeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="optimizeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OptimizeRequest optimizeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (optimizeRequest.Parts == null)
                throw new ArgumentNullException(nameof(optimizeRequest.Parts), "Property is required for class OptimizeRequest.");

            if (optimizeRequest.Sheets == null)
                throw new ArgumentNullException(nameof(optimizeRequest.Sheets), "Property is required for class OptimizeRequest.");

            if (optimizeRequest.Machine == null)
                throw new ArgumentNullException(nameof(optimizeRequest.Machine), "Property is required for class OptimizeRequest.");

            if (optimizeRequest.CostTariffsOption.IsSet && optimizeRequest.CostTariffs == null)
                throw new ArgumentNullException(nameof(optimizeRequest.CostTariffs), "Property is required for class OptimizeRequest.");

            writer.WritePropertyName("parts");
            JsonSerializer.Serialize(writer, optimizeRequest.Parts, jsonSerializerOptions);
            writer.WritePropertyName("sheets");
            JsonSerializer.Serialize(writer, optimizeRequest.Sheets, jsonSerializerOptions);
            writer.WritePropertyName("machine");
            JsonSerializer.Serialize(writer, optimizeRequest.Machine, jsonSerializerOptions);
            var strategyRawValue = OptimizeRequest.StrategyEnumToJsonValue(optimizeRequest.StrategyOption.Value!.Value);
            writer.WriteString("strategy", strategyRawValue);
            if (optimizeRequest.CostTariffsOption.IsSet)
            {
                writer.WritePropertyName("cost_tariffs");
                JsonSerializer.Serialize(writer, optimizeRequest.CostTariffs, jsonSerializerOptions);
            }
        }
    }
}
