// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// OptimizeAccepted
    /// </summary>
    public partial class OptimizeAccepted : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OptimizeAccepted" /> class.
        /// </summary>
        /// <param name="jobId">jobId</param>
        /// <param name="status">status</param>
        /// <param name="pollUrl">pollUrl</param>
        /// <param name="streamUrl">streamUrl</param>
        [JsonConstructor]
        public OptimizeAccepted(Guid jobId, string status, string pollUrl, string streamUrl)
        {
            JobId = jobId;
            Status = status;
            PollUrl = pollUrl;
            StreamUrl = streamUrl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [JsonPropertyName("job_id")]
        public Guid JobId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /* <example>pending</example> */
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets PollUrl
        /// </summary>
        /* <example>/v1/jobs/550e8400-e29b-41d4-a716-446655440000</example> */
        [JsonPropertyName("poll_url")]
        public string PollUrl { get; set; }

        /// <summary>
        /// Gets or Sets StreamUrl
        /// </summary>
        /* <example>/v1/jobs/550e8400-e29b-41d4-a716-446655440000/stream</example> */
        [JsonPropertyName("stream_url")]
        public string StreamUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OptimizeAccepted {\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  PollUrl: ").Append(PollUrl).Append("\n");
            sb.Append("  StreamUrl: ").Append(StreamUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OptimizeAccepted" />
    /// </summary>
    public class OptimizeAcceptedJsonConverter : JsonConverter<OptimizeAccepted>
    {
        /// <summary>
        /// Deserializes json to <see cref="OptimizeAccepted" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OptimizeAccepted Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> jobId = default;
            Option<string?> status = default;
            Option<string?> pollUrl = default;
            Option<string?> streamUrl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "job_id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                jobId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "poll_url":
                            pollUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "stream_url":
                            streamUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!jobId.IsSet)
                throw new ArgumentException("Property is required for class OptimizeAccepted.", nameof(jobId));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class OptimizeAccepted.", nameof(status));

            if (!pollUrl.IsSet)
                throw new ArgumentException("Property is required for class OptimizeAccepted.", nameof(pollUrl));

            if (!streamUrl.IsSet)
                throw new ArgumentException("Property is required for class OptimizeAccepted.", nameof(streamUrl));

            if (jobId.IsSet && jobId.Value == null)
                throw new ArgumentNullException(nameof(jobId), "Property is not nullable for class OptimizeAccepted.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class OptimizeAccepted.");

            if (pollUrl.IsSet && pollUrl.Value == null)
                throw new ArgumentNullException(nameof(pollUrl), "Property is not nullable for class OptimizeAccepted.");

            if (streamUrl.IsSet && streamUrl.Value == null)
                throw new ArgumentNullException(nameof(streamUrl), "Property is not nullable for class OptimizeAccepted.");

            return new OptimizeAccepted(jobId.Value!.Value!, status.Value!, pollUrl.Value!, streamUrl.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OptimizeAccepted" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="optimizeAccepted"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OptimizeAccepted optimizeAccepted, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, optimizeAccepted, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OptimizeAccepted" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="optimizeAccepted"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OptimizeAccepted optimizeAccepted, JsonSerializerOptions jsonSerializerOptions)
        {
            if (optimizeAccepted.Status == null)
                throw new ArgumentNullException(nameof(optimizeAccepted.Status), "Property is required for class OptimizeAccepted.");

            if (optimizeAccepted.PollUrl == null)
                throw new ArgumentNullException(nameof(optimizeAccepted.PollUrl), "Property is required for class OptimizeAccepted.");

            if (optimizeAccepted.StreamUrl == null)
                throw new ArgumentNullException(nameof(optimizeAccepted.StreamUrl), "Property is required for class OptimizeAccepted.");

            writer.WriteString("job_id", optimizeAccepted.JobId);

            writer.WriteString("status", optimizeAccepted.Status);

            writer.WriteString("poll_url", optimizeAccepted.PollUrl);

            writer.WriteString("stream_url", optimizeAccepted.StreamUrl);
        }
    }
}
