// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Part
    /// </summary>
    public partial class Part : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Part" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="length">Length in mm</param>
        /// <param name="width">Width in mm</param>
        /// <param name="quantity">quantity</param>
        /// <param name="grain">grain</param>
        /// <param name="edgeBanding">edgeBanding</param>
        [JsonConstructor]
        public Part(string id, double length, double width, int quantity, GrainDirection grain, Option<EdgeCorrection?> edgeBanding = default)
        {
            Id = id;
            Length = length;
            Width = width;
            Quantity = quantity;
            Grain = grain;
            EdgeBandingOption = edgeBanding;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Grain
        /// </summary>
        [JsonPropertyName("grain")]
        public GrainDirection Grain { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Length in mm
        /// </summary>
        /// <value>Length in mm</value>
        [JsonPropertyName("length")]
        public double Length { get; set; }

        /// <summary>
        /// Width in mm
        /// </summary>
        /// <value>Width in mm</value>
        [JsonPropertyName("width")]
        public double Width { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [JsonPropertyName("quantity")]
        public int Quantity { get; set; }

        /// <summary>
        /// Used to track the state of EdgeBanding
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EdgeCorrection?> EdgeBandingOption { get; private set; }

        /// <summary>
        /// Gets or Sets EdgeBanding
        /// </summary>
        [JsonPropertyName("edge_banding")]
        public EdgeCorrection? EdgeBanding { get { return this.EdgeBandingOption; } set { this.EdgeBandingOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Part {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Grain: ").Append(Grain).Append("\n");
            sb.Append("  EdgeBanding: ").Append(EdgeBanding).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Quantity (int) minimum
            if (this.Quantity < (int)1)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value greater than or equal to 1.", new [] { "Quantity" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Part" />
    /// </summary>
    public class PartJsonConverter : JsonConverter<Part>
    {
        /// <summary>
        /// Deserializes json to <see cref="Part" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Part Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<double?> length = default;
            Option<double?> width = default;
            Option<int?> quantity = default;
            Option<GrainDirection?> grain = default;
            Option<EdgeCorrection?> edgeBanding = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "length":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                length = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "width":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                width = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "quantity":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                quantity = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "grain":
                            string? grainRawValue = utf8JsonReader.GetString();
                            if (grainRawValue != null)
                                grain = new Option<GrainDirection?>(GrainDirectionValueConverter.FromStringOrDefault(grainRawValue));
                            break;
                        case "edge_banding":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                edgeBanding = new Option<EdgeCorrection?>(JsonSerializer.Deserialize<EdgeCorrection>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Part.", nameof(id));

            if (!length.IsSet)
                throw new ArgumentException("Property is required for class Part.", nameof(length));

            if (!width.IsSet)
                throw new ArgumentException("Property is required for class Part.", nameof(width));

            if (!quantity.IsSet)
                throw new ArgumentException("Property is required for class Part.", nameof(quantity));

            if (!grain.IsSet)
                throw new ArgumentException("Property is required for class Part.", nameof(grain));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Part.");

            if (length.IsSet && length.Value == null)
                throw new ArgumentNullException(nameof(length), "Property is not nullable for class Part.");

            if (width.IsSet && width.Value == null)
                throw new ArgumentNullException(nameof(width), "Property is not nullable for class Part.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class Part.");

            if (grain.IsSet && grain.Value == null)
                throw new ArgumentNullException(nameof(grain), "Property is not nullable for class Part.");

            if (edgeBanding.IsSet && edgeBanding.Value == null)
                throw new ArgumentNullException(nameof(edgeBanding), "Property is not nullable for class Part.");

            return new Part(id.Value!, length.Value!.Value!, width.Value!.Value!, quantity.Value!.Value!, grain.Value!.Value!, edgeBanding);
        }

        /// <summary>
        /// Serializes a <see cref="Part" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="part"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Part part, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, part, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Part" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="part"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Part part, JsonSerializerOptions jsonSerializerOptions)
        {
            if (part.Id == null)
                throw new ArgumentNullException(nameof(part.Id), "Property is required for class Part.");

            if (part.EdgeBandingOption.IsSet && part.EdgeBanding == null)
                throw new ArgumentNullException(nameof(part.EdgeBanding), "Property is required for class Part.");

            writer.WriteString("id", part.Id);

            writer.WriteNumber("length", part.Length);

            writer.WriteNumber("width", part.Width);

            writer.WriteNumber("quantity", part.Quantity);

            var grainRawValue = GrainDirectionValueConverter.ToJsonValue(part.Grain);
            writer.WriteString("grain", grainRawValue);

            if (part.EdgeBandingOption.IsSet)
            {
                writer.WritePropertyName("edge_banding");
                JsonSerializer.Serialize(writer, part.EdgeBanding, jsonSerializerOptions);
            }
        }
    }
}
