// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Placement
    /// </summary>
    public partial class Placement : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Placement" /> class.
        /// </summary>
        /// <param name="partId">partId</param>
        /// <param name="sheetId">Which sheet type this part is placed on</param>
        /// <param name="x">mm from top-left of usable area</param>
        /// <param name="y">mm from top-left of usable area</param>
        /// <param name="width">Post-edge-banding dimension</param>
        /// <param name="height">Post-edge-banding dimension</param>
        /// <param name="rotated">rotated</param>
        /// <param name="grain">grain</param>
        [JsonConstructor]
        public Placement(string partId, string sheetId, double x, double y, double width, double height, bool rotated, GrainDirection grain)
        {
            PartId = partId;
            SheetId = sheetId;
            X = x;
            Y = y;
            Width = width;
            Height = height;
            Rotated = rotated;
            Grain = grain;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Grain
        /// </summary>
        [JsonPropertyName("grain")]
        public GrainDirection Grain { get; set; }

        /// <summary>
        /// Gets or Sets PartId
        /// </summary>
        [JsonPropertyName("part_id")]
        public string PartId { get; set; }

        /// <summary>
        /// Which sheet type this part is placed on
        /// </summary>
        /// <value>Which sheet type this part is placed on</value>
        [JsonPropertyName("sheet_id")]
        public string SheetId { get; set; }

        /// <summary>
        /// mm from top-left of usable area
        /// </summary>
        /// <value>mm from top-left of usable area</value>
        [JsonPropertyName("x")]
        public double X { get; set; }

        /// <summary>
        /// mm from top-left of usable area
        /// </summary>
        /// <value>mm from top-left of usable area</value>
        [JsonPropertyName("y")]
        public double Y { get; set; }

        /// <summary>
        /// Post-edge-banding dimension
        /// </summary>
        /// <value>Post-edge-banding dimension</value>
        [JsonPropertyName("width")]
        public double Width { get; set; }

        /// <summary>
        /// Post-edge-banding dimension
        /// </summary>
        /// <value>Post-edge-banding dimension</value>
        [JsonPropertyName("height")]
        public double Height { get; set; }

        /// <summary>
        /// Gets or Sets Rotated
        /// </summary>
        [JsonPropertyName("rotated")]
        public bool Rotated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Placement {\n");
            sb.Append("  PartId: ").Append(PartId).Append("\n");
            sb.Append("  SheetId: ").Append(SheetId).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Rotated: ").Append(Rotated).Append("\n");
            sb.Append("  Grain: ").Append(Grain).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Placement" />
    /// </summary>
    public class PlacementJsonConverter : JsonConverter<Placement>
    {
        /// <summary>
        /// Deserializes json to <see cref="Placement" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Placement Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> partId = default;
            Option<string?> sheetId = default;
            Option<double?> x = default;
            Option<double?> y = default;
            Option<double?> width = default;
            Option<double?> height = default;
            Option<bool?> rotated = default;
            Option<GrainDirection?> grain = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "part_id":
                            partId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sheet_id":
                            sheetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "x":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                x = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "y":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                y = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "width":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                width = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "height":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                height = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "rotated":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                rotated = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "grain":
                            string? grainRawValue = utf8JsonReader.GetString();
                            if (grainRawValue != null)
                                grain = new Option<GrainDirection?>(GrainDirectionValueConverter.FromStringOrDefault(grainRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!partId.IsSet)
                throw new ArgumentException("Property is required for class Placement.", nameof(partId));

            if (!sheetId.IsSet)
                throw new ArgumentException("Property is required for class Placement.", nameof(sheetId));

            if (!x.IsSet)
                throw new ArgumentException("Property is required for class Placement.", nameof(x));

            if (!y.IsSet)
                throw new ArgumentException("Property is required for class Placement.", nameof(y));

            if (!width.IsSet)
                throw new ArgumentException("Property is required for class Placement.", nameof(width));

            if (!height.IsSet)
                throw new ArgumentException("Property is required for class Placement.", nameof(height));

            if (!rotated.IsSet)
                throw new ArgumentException("Property is required for class Placement.", nameof(rotated));

            if (!grain.IsSet)
                throw new ArgumentException("Property is required for class Placement.", nameof(grain));

            if (partId.IsSet && partId.Value == null)
                throw new ArgumentNullException(nameof(partId), "Property is not nullable for class Placement.");

            if (sheetId.IsSet && sheetId.Value == null)
                throw new ArgumentNullException(nameof(sheetId), "Property is not nullable for class Placement.");

            if (x.IsSet && x.Value == null)
                throw new ArgumentNullException(nameof(x), "Property is not nullable for class Placement.");

            if (y.IsSet && y.Value == null)
                throw new ArgumentNullException(nameof(y), "Property is not nullable for class Placement.");

            if (width.IsSet && width.Value == null)
                throw new ArgumentNullException(nameof(width), "Property is not nullable for class Placement.");

            if (height.IsSet && height.Value == null)
                throw new ArgumentNullException(nameof(height), "Property is not nullable for class Placement.");

            if (rotated.IsSet && rotated.Value == null)
                throw new ArgumentNullException(nameof(rotated), "Property is not nullable for class Placement.");

            if (grain.IsSet && grain.Value == null)
                throw new ArgumentNullException(nameof(grain), "Property is not nullable for class Placement.");

            return new Placement(partId.Value!, sheetId.Value!, x.Value!.Value!, y.Value!.Value!, width.Value!.Value!, height.Value!.Value!, rotated.Value!.Value!, grain.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Placement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="placement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Placement placement, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, placement, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Placement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="placement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Placement placement, JsonSerializerOptions jsonSerializerOptions)
        {
            if (placement.PartId == null)
                throw new ArgumentNullException(nameof(placement.PartId), "Property is required for class Placement.");

            if (placement.SheetId == null)
                throw new ArgumentNullException(nameof(placement.SheetId), "Property is required for class Placement.");

            writer.WriteString("part_id", placement.PartId);

            writer.WriteString("sheet_id", placement.SheetId);

            writer.WriteNumber("x", placement.X);

            writer.WriteNumber("y", placement.Y);

            writer.WriteNumber("width", placement.Width);

            writer.WriteNumber("height", placement.Height);

            writer.WriteBoolean("rotated", placement.Rotated);

            var grainRawValue = GrainDirectionValueConverter.ToJsonValue(placement.Grain);
            writer.WriteString("grain", grainRawValue);
        }
    }
}
