// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// RateLimitError
    /// </summary>
    public partial class RateLimitError : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RateLimitError" /> class.
        /// </summary>
        /// <param name="error">error</param>
        /// <param name="limit">Request limit for this tier and strategy (24h sliding window)</param>
        /// <param name="remaining">Remaining requests in the current window</param>
        /// <param name="strategy">Which strategy quota was exceeded</param>
        [JsonConstructor]
        public RateLimitError(string error, int limit, int remaining, StrategyEnum strategy)
        {
            Error = error;
            Limit = limit;
            Remaining = remaining;
            Strategy = strategy;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Which strategy quota was exceeded
        /// </summary>
        /// <value>Which strategy quota was exceeded</value>
        public enum StrategyEnum
        {
            /// <summary>
            /// Enum Fast for value: fast
            /// </summary>
            Fast = 1,

            /// <summary>
            /// Enum Thorough for value: thorough
            /// </summary>
            Thorough = 2
        }

        /// <summary>
        /// Returns a <see cref="StrategyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StrategyEnum StrategyEnumFromString(string value)
        {
            if (value.Equals("fast"))
                return StrategyEnum.Fast;

            if (value.Equals("thorough"))
                return StrategyEnum.Thorough;

            throw new NotImplementedException($"Could not convert value to type StrategyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StrategyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StrategyEnum? StrategyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("fast"))
                return StrategyEnum.Fast;

            if (value.Equals("thorough"))
                return StrategyEnum.Thorough;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StrategyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StrategyEnumToJsonValue(StrategyEnum value)
        {
            if (value == StrategyEnum.Fast)
                return "fast";

            if (value == StrategyEnum.Thorough)
                return "thorough";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Which strategy quota was exceeded
        /// </summary>
        /// <value>Which strategy quota was exceeded</value>
        [JsonPropertyName("strategy")]
        public StrategyEnum Strategy { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        /* <example>rate limit exceeded</example> */
        [JsonPropertyName("error")]
        public string Error { get; set; }

        /// <summary>
        /// Request limit for this tier and strategy (24h sliding window)
        /// </summary>
        /// <value>Request limit for this tier and strategy (24h sliding window)</value>
        [JsonPropertyName("limit")]
        public int Limit { get; set; }

        /// <summary>
        /// Remaining requests in the current window
        /// </summary>
        /// <value>Remaining requests in the current window</value>
        [JsonPropertyName("remaining")]
        public int Remaining { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RateLimitError {\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Remaining: ").Append(Remaining).Append("\n");
            sb.Append("  Strategy: ").Append(Strategy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RateLimitError" />
    /// </summary>
    public class RateLimitErrorJsonConverter : JsonConverter<RateLimitError>
    {
        /// <summary>
        /// Deserializes json to <see cref="RateLimitError" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RateLimitError Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> error = default;
            Option<int?> limit = default;
            Option<int?> remaining = default;
            Option<RateLimitError.StrategyEnum?> strategy = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "error":
                            error = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "limit":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                limit = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "remaining":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                remaining = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "strategy":
                            string? strategyRawValue = utf8JsonReader.GetString();
                            if (strategyRawValue != null)
                                strategy = new Option<RateLimitError.StrategyEnum?>(RateLimitError.StrategyEnumFromStringOrDefault(strategyRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!error.IsSet)
                throw new ArgumentException("Property is required for class RateLimitError.", nameof(error));

            if (!limit.IsSet)
                throw new ArgumentException("Property is required for class RateLimitError.", nameof(limit));

            if (!remaining.IsSet)
                throw new ArgumentException("Property is required for class RateLimitError.", nameof(remaining));

            if (!strategy.IsSet)
                throw new ArgumentException("Property is required for class RateLimitError.", nameof(strategy));

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class RateLimitError.");

            if (limit.IsSet && limit.Value == null)
                throw new ArgumentNullException(nameof(limit), "Property is not nullable for class RateLimitError.");

            if (remaining.IsSet && remaining.Value == null)
                throw new ArgumentNullException(nameof(remaining), "Property is not nullable for class RateLimitError.");

            if (strategy.IsSet && strategy.Value == null)
                throw new ArgumentNullException(nameof(strategy), "Property is not nullable for class RateLimitError.");

            return new RateLimitError(error.Value!, limit.Value!.Value!, remaining.Value!.Value!, strategy.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RateLimitError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rateLimitError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RateLimitError rateLimitError, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, rateLimitError, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RateLimitError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rateLimitError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RateLimitError rateLimitError, JsonSerializerOptions jsonSerializerOptions)
        {
            if (rateLimitError.Error == null)
                throw new ArgumentNullException(nameof(rateLimitError.Error), "Property is required for class RateLimitError.");

            writer.WriteString("error", rateLimitError.Error);

            writer.WriteNumber("limit", rateLimitError.Limit);

            writer.WriteNumber("remaining", rateLimitError.Remaining);

            var strategyRawValue = RateLimitError.StrategyEnumToJsonValue(rateLimitError.Strategy);
            writer.WriteString("strategy", strategyRawValue);
        }
    }
}
