// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Sheet
    /// </summary>
    public partial class Sheet : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Sheet" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="length">Length in mm</param>
        /// <param name="width">Width in mm</param>
        /// <param name="quantity">0 &#x3D; unlimited</param>
        /// <param name="grain">grain</param>
        /// <param name="isOffcut">Offcut sheets are prioritized by the solver (default to false)</param>
        /// <param name="trimMargins">trimMargins</param>
        /// <param name="articleNumber">Optional article/SKU reference for this sheet type</param>
        [JsonConstructor]
        public Sheet(string id, double length, double width, int quantity, GrainDirection grain, Option<bool?> isOffcut = default, Option<Margins?> trimMargins = default, Option<string?> articleNumber = default)
        {
            Id = id;
            Length = length;
            Width = width;
            Quantity = quantity;
            Grain = grain;
            IsOffcutOption = isOffcut;
            TrimMarginsOption = trimMargins;
            ArticleNumberOption = articleNumber;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Grain
        /// </summary>
        [JsonPropertyName("grain")]
        public GrainDirection Grain { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Length in mm
        /// </summary>
        /// <value>Length in mm</value>
        [JsonPropertyName("length")]
        public double Length { get; set; }

        /// <summary>
        /// Width in mm
        /// </summary>
        /// <value>Width in mm</value>
        [JsonPropertyName("width")]
        public double Width { get; set; }

        /// <summary>
        /// 0 &#x3D; unlimited
        /// </summary>
        /// <value>0 &#x3D; unlimited</value>
        [JsonPropertyName("quantity")]
        public int Quantity { get; set; }

        /// <summary>
        /// Used to track the state of IsOffcut
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsOffcutOption { get; private set; }

        /// <summary>
        /// Offcut sheets are prioritized by the solver
        /// </summary>
        /// <value>Offcut sheets are prioritized by the solver</value>
        [JsonPropertyName("is_offcut")]
        public bool? IsOffcut { get { return this.IsOffcutOption; } set { this.IsOffcutOption = new(value); } }

        /// <summary>
        /// Used to track the state of TrimMargins
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Margins?> TrimMarginsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TrimMargins
        /// </summary>
        [JsonPropertyName("trim_margins")]
        public Margins? TrimMargins { get { return this.TrimMarginsOption; } set { this.TrimMarginsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ArticleNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ArticleNumberOption { get; private set; }

        /// <summary>
        /// Optional article/SKU reference for this sheet type
        /// </summary>
        /// <value>Optional article/SKU reference for this sheet type</value>
        [JsonPropertyName("article_number")]
        public string? ArticleNumber { get { return this.ArticleNumberOption; } set { this.ArticleNumberOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Sheet {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Grain: ").Append(Grain).Append("\n");
            sb.Append("  IsOffcut: ").Append(IsOffcut).Append("\n");
            sb.Append("  TrimMargins: ").Append(TrimMargins).Append("\n");
            sb.Append("  ArticleNumber: ").Append(ArticleNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Quantity (int) minimum
            if (this.Quantity < (int)0)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value greater than or equal to 0.", new [] { "Quantity" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Sheet" />
    /// </summary>
    public class SheetJsonConverter : JsonConverter<Sheet>
    {
        /// <summary>
        /// Deserializes json to <see cref="Sheet" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Sheet Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<double?> length = default;
            Option<double?> width = default;
            Option<int?> quantity = default;
            Option<GrainDirection?> grain = default;
            Option<bool?> isOffcut = default;
            Option<Margins?> trimMargins = default;
            Option<string?> articleNumber = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "length":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                length = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "width":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                width = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "quantity":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                quantity = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "grain":
                            string? grainRawValue = utf8JsonReader.GetString();
                            if (grainRawValue != null)
                                grain = new Option<GrainDirection?>(GrainDirectionValueConverter.FromStringOrDefault(grainRawValue));
                            break;
                        case "is_offcut":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isOffcut = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "trim_margins":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                trimMargins = new Option<Margins?>(JsonSerializer.Deserialize<Margins>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "article_number":
                            articleNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Sheet.", nameof(id));

            if (!length.IsSet)
                throw new ArgumentException("Property is required for class Sheet.", nameof(length));

            if (!width.IsSet)
                throw new ArgumentException("Property is required for class Sheet.", nameof(width));

            if (!quantity.IsSet)
                throw new ArgumentException("Property is required for class Sheet.", nameof(quantity));

            if (!grain.IsSet)
                throw new ArgumentException("Property is required for class Sheet.", nameof(grain));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Sheet.");

            if (length.IsSet && length.Value == null)
                throw new ArgumentNullException(nameof(length), "Property is not nullable for class Sheet.");

            if (width.IsSet && width.Value == null)
                throw new ArgumentNullException(nameof(width), "Property is not nullable for class Sheet.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class Sheet.");

            if (grain.IsSet && grain.Value == null)
                throw new ArgumentNullException(nameof(grain), "Property is not nullable for class Sheet.");

            if (isOffcut.IsSet && isOffcut.Value == null)
                throw new ArgumentNullException(nameof(isOffcut), "Property is not nullable for class Sheet.");

            if (trimMargins.IsSet && trimMargins.Value == null)
                throw new ArgumentNullException(nameof(trimMargins), "Property is not nullable for class Sheet.");

            if (articleNumber.IsSet && articleNumber.Value == null)
                throw new ArgumentNullException(nameof(articleNumber), "Property is not nullable for class Sheet.");

            return new Sheet(id.Value!, length.Value!.Value!, width.Value!.Value!, quantity.Value!.Value!, grain.Value!.Value!, isOffcut, trimMargins, articleNumber);
        }

        /// <summary>
        /// Serializes a <see cref="Sheet" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sheet"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Sheet sheet, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sheet, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Sheet" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sheet"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Sheet sheet, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sheet.Id == null)
                throw new ArgumentNullException(nameof(sheet.Id), "Property is required for class Sheet.");

            if (sheet.TrimMarginsOption.IsSet && sheet.TrimMargins == null)
                throw new ArgumentNullException(nameof(sheet.TrimMargins), "Property is required for class Sheet.");

            if (sheet.ArticleNumberOption.IsSet && sheet.ArticleNumber == null)
                throw new ArgumentNullException(nameof(sheet.ArticleNumber), "Property is required for class Sheet.");

            writer.WriteString("id", sheet.Id);

            writer.WriteNumber("length", sheet.Length);

            writer.WriteNumber("width", sheet.Width);

            writer.WriteNumber("quantity", sheet.Quantity);

            var grainRawValue = GrainDirectionValueConverter.ToJsonValue(sheet.Grain);
            writer.WriteString("grain", grainRawValue);

            if (sheet.IsOffcutOption.IsSet)
                writer.WriteBoolean("is_offcut", sheet.IsOffcutOption.Value!.Value);

            if (sheet.TrimMarginsOption.IsSet)
            {
                writer.WritePropertyName("trim_margins");
                JsonSerializer.Serialize(writer, sheet.TrimMargins, jsonSerializerOptions);
            }
            if (sheet.ArticleNumberOption.IsSet)
                writer.WriteString("article_number", sheet.ArticleNumber);
        }
    }
}
