// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// SheetUsage
    /// </summary>
    public partial class SheetUsage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SheetUsage" /> class.
        /// </summary>
        /// <param name="sheetId">sheetId</param>
        /// <param name="quantity">Number of this sheet type consumed</param>
        /// <param name="yieldPercent">Yield percentage for this sheet type</param>
        /// <param name="articleNumber">Article/SKU reference (from request, if provided)</param>
        [JsonConstructor]
        public SheetUsage(string sheetId, int quantity, double yieldPercent, Option<string?> articleNumber = default)
        {
            SheetId = sheetId;
            Quantity = quantity;
            YieldPercent = yieldPercent;
            ArticleNumberOption = articleNumber;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SheetId
        /// </summary>
        [JsonPropertyName("sheet_id")]
        public string SheetId { get; set; }

        /// <summary>
        /// Number of this sheet type consumed
        /// </summary>
        /// <value>Number of this sheet type consumed</value>
        [JsonPropertyName("quantity")]
        public int Quantity { get; set; }

        /// <summary>
        /// Yield percentage for this sheet type
        /// </summary>
        /// <value>Yield percentage for this sheet type</value>
        [JsonPropertyName("yield_percent")]
        public double YieldPercent { get; set; }

        /// <summary>
        /// Used to track the state of ArticleNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ArticleNumberOption { get; private set; }

        /// <summary>
        /// Article/SKU reference (from request, if provided)
        /// </summary>
        /// <value>Article/SKU reference (from request, if provided)</value>
        [JsonPropertyName("article_number")]
        public string? ArticleNumber { get { return this.ArticleNumberOption; } set { this.ArticleNumberOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SheetUsage {\n");
            sb.Append("  SheetId: ").Append(SheetId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  YieldPercent: ").Append(YieldPercent).Append("\n");
            sb.Append("  ArticleNumber: ").Append(ArticleNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // YieldPercent (double) maximum
            if (this.YieldPercent > (double)100)
            {
                yield return new ValidationResult("Invalid value for YieldPercent, must be a value less than or equal to 100.", new [] { "YieldPercent" });
            }

            // YieldPercent (double) minimum
            if (this.YieldPercent < (double)0)
            {
                yield return new ValidationResult("Invalid value for YieldPercent, must be a value greater than or equal to 0.", new [] { "YieldPercent" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SheetUsage" />
    /// </summary>
    public class SheetUsageJsonConverter : JsonConverter<SheetUsage>
    {
        /// <summary>
        /// Deserializes json to <see cref="SheetUsage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SheetUsage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> sheetId = default;
            Option<int?> quantity = default;
            Option<double?> yieldPercent = default;
            Option<string?> articleNumber = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sheet_id":
                            sheetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "quantity":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                quantity = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "yield_percent":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                yieldPercent = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "article_number":
                            articleNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!sheetId.IsSet)
                throw new ArgumentException("Property is required for class SheetUsage.", nameof(sheetId));

            if (!quantity.IsSet)
                throw new ArgumentException("Property is required for class SheetUsage.", nameof(quantity));

            if (!yieldPercent.IsSet)
                throw new ArgumentException("Property is required for class SheetUsage.", nameof(yieldPercent));

            if (sheetId.IsSet && sheetId.Value == null)
                throw new ArgumentNullException(nameof(sheetId), "Property is not nullable for class SheetUsage.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class SheetUsage.");

            if (yieldPercent.IsSet && yieldPercent.Value == null)
                throw new ArgumentNullException(nameof(yieldPercent), "Property is not nullable for class SheetUsage.");

            if (articleNumber.IsSet && articleNumber.Value == null)
                throw new ArgumentNullException(nameof(articleNumber), "Property is not nullable for class SheetUsage.");

            return new SheetUsage(sheetId.Value!, quantity.Value!.Value!, yieldPercent.Value!.Value!, articleNumber);
        }

        /// <summary>
        /// Serializes a <see cref="SheetUsage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sheetUsage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SheetUsage sheetUsage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sheetUsage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SheetUsage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sheetUsage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SheetUsage sheetUsage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sheetUsage.SheetId == null)
                throw new ArgumentNullException(nameof(sheetUsage.SheetId), "Property is required for class SheetUsage.");

            if (sheetUsage.ArticleNumberOption.IsSet && sheetUsage.ArticleNumber == null)
                throw new ArgumentNullException(nameof(sheetUsage.ArticleNumber), "Property is required for class SheetUsage.");

            writer.WriteString("sheet_id", sheetUsage.SheetId);

            writer.WriteNumber("quantity", sheetUsage.Quantity);

            writer.WriteNumber("yield_percent", sheetUsage.YieldPercent);

            if (sheetUsage.ArticleNumberOption.IsSet)
                writer.WriteString("article_number", sheetUsage.ArticleNumber);
        }
    }
}
