// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// Summary
    /// </summary>
    public partial class Summary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Summary" /> class.
        /// </summary>
        /// <param name="totalSheets">totalSheets</param>
        /// <param name="yieldPercent">yieldPercent</param>
        /// <param name="wastePercent">wastePercent</param>
        /// <param name="wasteArea">mm²</param>
        /// <param name="sheetsUsed">sheetsUsed</param>
        /// <param name="unplacedParts">unplacedParts</param>
        [JsonConstructor]
        public Summary(int totalSheets, double yieldPercent, double wastePercent, double wasteArea, List<SheetUsage> sheetsUsed, Option<List<string>?> unplacedParts = default)
        {
            TotalSheets = totalSheets;
            YieldPercent = yieldPercent;
            WastePercent = wastePercent;
            WasteArea = wasteArea;
            SheetsUsed = sheetsUsed;
            UnplacedPartsOption = unplacedParts;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets TotalSheets
        /// </summary>
        [JsonPropertyName("total_sheets")]
        public int TotalSheets { get; set; }

        /// <summary>
        /// Gets or Sets YieldPercent
        /// </summary>
        [JsonPropertyName("yield_percent")]
        public double YieldPercent { get; set; }

        /// <summary>
        /// Gets or Sets WastePercent
        /// </summary>
        [JsonPropertyName("waste_percent")]
        public double WastePercent { get; set; }

        /// <summary>
        /// mm²
        /// </summary>
        /// <value>mm²</value>
        [JsonPropertyName("waste_area")]
        public double WasteArea { get; set; }

        /// <summary>
        /// Gets or Sets SheetsUsed
        /// </summary>
        [JsonPropertyName("sheets_used")]
        public List<SheetUsage> SheetsUsed { get; set; }

        /// <summary>
        /// Used to track the state of UnplacedParts
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> UnplacedPartsOption { get; private set; }

        /// <summary>
        /// Gets or Sets UnplacedParts
        /// </summary>
        [JsonPropertyName("unplaced_parts")]
        public List<string>? UnplacedParts { get { return this.UnplacedPartsOption; } set { this.UnplacedPartsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Summary {\n");
            sb.Append("  TotalSheets: ").Append(TotalSheets).Append("\n");
            sb.Append("  YieldPercent: ").Append(YieldPercent).Append("\n");
            sb.Append("  WastePercent: ").Append(WastePercent).Append("\n");
            sb.Append("  WasteArea: ").Append(WasteArea).Append("\n");
            sb.Append("  SheetsUsed: ").Append(SheetsUsed).Append("\n");
            sb.Append("  UnplacedParts: ").Append(UnplacedParts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // YieldPercent (double) maximum
            if (this.YieldPercent > (double)100)
            {
                yield return new ValidationResult("Invalid value for YieldPercent, must be a value less than or equal to 100.", new [] { "YieldPercent" });
            }

            // YieldPercent (double) minimum
            if (this.YieldPercent < (double)0)
            {
                yield return new ValidationResult("Invalid value for YieldPercent, must be a value greater than or equal to 0.", new [] { "YieldPercent" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Summary" />
    /// </summary>
    public class SummaryJsonConverter : JsonConverter<Summary>
    {
        /// <summary>
        /// Deserializes json to <see cref="Summary" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Summary Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> totalSheets = default;
            Option<double?> yieldPercent = default;
            Option<double?> wastePercent = default;
            Option<double?> wasteArea = default;
            Option<List<SheetUsage>?> sheetsUsed = default;
            Option<List<string>?> unplacedParts = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "total_sheets":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                totalSheets = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "yield_percent":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                yieldPercent = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "waste_percent":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                wastePercent = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "waste_area":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                wasteArea = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "sheets_used":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                sheetsUsed = new Option<List<SheetUsage>?>(JsonSerializer.Deserialize<List<SheetUsage>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "unplaced_parts":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                unplacedParts = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!totalSheets.IsSet)
                throw new ArgumentException("Property is required for class Summary.", nameof(totalSheets));

            if (!yieldPercent.IsSet)
                throw new ArgumentException("Property is required for class Summary.", nameof(yieldPercent));

            if (!wastePercent.IsSet)
                throw new ArgumentException("Property is required for class Summary.", nameof(wastePercent));

            if (!wasteArea.IsSet)
                throw new ArgumentException("Property is required for class Summary.", nameof(wasteArea));

            if (!sheetsUsed.IsSet)
                throw new ArgumentException("Property is required for class Summary.", nameof(sheetsUsed));

            if (totalSheets.IsSet && totalSheets.Value == null)
                throw new ArgumentNullException(nameof(totalSheets), "Property is not nullable for class Summary.");

            if (yieldPercent.IsSet && yieldPercent.Value == null)
                throw new ArgumentNullException(nameof(yieldPercent), "Property is not nullable for class Summary.");

            if (wastePercent.IsSet && wastePercent.Value == null)
                throw new ArgumentNullException(nameof(wastePercent), "Property is not nullable for class Summary.");

            if (wasteArea.IsSet && wasteArea.Value == null)
                throw new ArgumentNullException(nameof(wasteArea), "Property is not nullable for class Summary.");

            if (sheetsUsed.IsSet && sheetsUsed.Value == null)
                throw new ArgumentNullException(nameof(sheetsUsed), "Property is not nullable for class Summary.");

            if (unplacedParts.IsSet && unplacedParts.Value == null)
                throw new ArgumentNullException(nameof(unplacedParts), "Property is not nullable for class Summary.");

            return new Summary(totalSheets.Value!.Value!, yieldPercent.Value!.Value!, wastePercent.Value!.Value!, wasteArea.Value!.Value!, sheetsUsed.Value!, unplacedParts);
        }

        /// <summary>
        /// Serializes a <see cref="Summary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="summary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Summary summary, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, summary, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Summary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="summary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Summary summary, JsonSerializerOptions jsonSerializerOptions)
        {
            if (summary.SheetsUsed == null)
                throw new ArgumentNullException(nameof(summary.SheetsUsed), "Property is required for class Summary.");

            if (summary.UnplacedPartsOption.IsSet && summary.UnplacedParts == null)
                throw new ArgumentNullException(nameof(summary.UnplacedParts), "Property is required for class Summary.");

            writer.WriteNumber("total_sheets", summary.TotalSheets);

            writer.WriteNumber("yield_percent", summary.YieldPercent);

            writer.WriteNumber("waste_percent", summary.WastePercent);

            writer.WriteNumber("waste_area", summary.WasteArea);

            writer.WritePropertyName("sheets_used");
            JsonSerializer.Serialize(writer, summary.SheetsUsed, jsonSerializerOptions);
            if (summary.UnplacedPartsOption.IsSet)
            {
                writer.WritePropertyName("unplaced_parts");
                JsonSerializer.Serialize(writer, summary.UnplacedParts, jsonSerializerOptions);
            }
        }
    }
}
