// <auto-generated>
/*
 * Sawvant Cutting Optimization API — .NET SDK
 *
 * File generated from our OpenAPI spec; DO NOT EDIT.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sawvant.Client;

namespace Sawvant.Model
{
    /// <summary>
    /// TierDefinition
    /// </summary>
    public partial class TierDefinition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TierDefinition" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="displayName">displayName</param>
        /// <param name="priceEurCents">priceEurCents</param>
        /// <param name="rateLimitFast">Maximum fast strategy requests per 24h sliding window</param>
        /// <param name="rateLimitThorough">Maximum thorough strategy requests per 24h sliding window</param>
        /// <param name="features">Feature gates enabled for this tier</param>
        /// <param name="period">period</param>
        [JsonConstructor]
        public TierDefinition(string name, string displayName, int priceEurCents, int rateLimitFast, int rateLimitThorough, Dictionary<string, bool> features, Option<string?> period = default)
        {
            Name = name;
            DisplayName = displayName;
            PriceEurCents = priceEurCents;
            RateLimitFast = rateLimitFast;
            RateLimitThorough = rateLimitThorough;
            Features = features;
            PeriodOption = period;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>pro</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        /* <example>Pro</example> */
        [JsonPropertyName("display_name")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets PriceEurCents
        /// </summary>
        /* <example>3900</example> */
        [JsonPropertyName("price_eur_cents")]
        public int PriceEurCents { get; set; }

        /// <summary>
        /// Maximum fast strategy requests per 24h sliding window
        /// </summary>
        /// <value>Maximum fast strategy requests per 24h sliding window</value>
        /* <example>100</example> */
        [JsonPropertyName("rate_limit_fast")]
        public int RateLimitFast { get; set; }

        /// <summary>
        /// Maximum thorough strategy requests per 24h sliding window
        /// </summary>
        /// <value>Maximum thorough strategy requests per 24h sliding window</value>
        /* <example>20</example> */
        [JsonPropertyName("rate_limit_thorough")]
        public int RateLimitThorough { get; set; }

        /// <summary>
        /// Feature gates enabled for this tier
        /// </summary>
        /// <value>Feature gates enabled for this tier</value>
        /* <example>{sse&#x3D;true, thorough&#x3D;true, metrics&#x3D;true, cost&#x3D;true}</example> */
        [JsonPropertyName("features")]
        public Dictionary<string, bool> Features { get; set; }

        /// <summary>
        /// Used to track the state of Period
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PeriodOption { get; private set; }

        /// <summary>
        /// Gets or Sets Period
        /// </summary>
        /* <example>month</example> */
        [JsonPropertyName("period")]
        public string? Period { get { return this.PeriodOption; } set { this.PeriodOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TierDefinition {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  PriceEurCents: ").Append(PriceEurCents).Append("\n");
            sb.Append("  RateLimitFast: ").Append(RateLimitFast).Append("\n");
            sb.Append("  RateLimitThorough: ").Append(RateLimitThorough).Append("\n");
            sb.Append("  Features: ").Append(Features).Append("\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TierDefinition" />
    /// </summary>
    public class TierDefinitionJsonConverter : JsonConverter<TierDefinition>
    {
        /// <summary>
        /// Deserializes json to <see cref="TierDefinition" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TierDefinition Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> displayName = default;
            Option<int?> priceEurCents = default;
            Option<int?> rateLimitFast = default;
            Option<int?> rateLimitThorough = default;
            Option<Dictionary<string, bool>?> features = default;
            Option<string?> period = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "display_name":
                            displayName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "price_eur_cents":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                priceEurCents = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "rate_limit_fast":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                rateLimitFast = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "rate_limit_thorough":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                rateLimitThorough = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "features":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                features = new Option<Dictionary<string, bool>?>(JsonSerializer.Deserialize<Dictionary<string, bool>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "period":
                            period = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class TierDefinition.", nameof(name));

            if (!displayName.IsSet)
                throw new ArgumentException("Property is required for class TierDefinition.", nameof(displayName));

            if (!priceEurCents.IsSet)
                throw new ArgumentException("Property is required for class TierDefinition.", nameof(priceEurCents));

            if (!rateLimitFast.IsSet)
                throw new ArgumentException("Property is required for class TierDefinition.", nameof(rateLimitFast));

            if (!rateLimitThorough.IsSet)
                throw new ArgumentException("Property is required for class TierDefinition.", nameof(rateLimitThorough));

            if (!features.IsSet)
                throw new ArgumentException("Property is required for class TierDefinition.", nameof(features));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class TierDefinition.");

            if (displayName.IsSet && displayName.Value == null)
                throw new ArgumentNullException(nameof(displayName), "Property is not nullable for class TierDefinition.");

            if (priceEurCents.IsSet && priceEurCents.Value == null)
                throw new ArgumentNullException(nameof(priceEurCents), "Property is not nullable for class TierDefinition.");

            if (rateLimitFast.IsSet && rateLimitFast.Value == null)
                throw new ArgumentNullException(nameof(rateLimitFast), "Property is not nullable for class TierDefinition.");

            if (rateLimitThorough.IsSet && rateLimitThorough.Value == null)
                throw new ArgumentNullException(nameof(rateLimitThorough), "Property is not nullable for class TierDefinition.");

            if (features.IsSet && features.Value == null)
                throw new ArgumentNullException(nameof(features), "Property is not nullable for class TierDefinition.");

            if (period.IsSet && period.Value == null)
                throw new ArgumentNullException(nameof(period), "Property is not nullable for class TierDefinition.");

            return new TierDefinition(name.Value!, displayName.Value!, priceEurCents.Value!.Value!, rateLimitFast.Value!.Value!, rateLimitThorough.Value!.Value!, features.Value!, period);
        }

        /// <summary>
        /// Serializes a <see cref="TierDefinition" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tierDefinition"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TierDefinition tierDefinition, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tierDefinition, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TierDefinition" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tierDefinition"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TierDefinition tierDefinition, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tierDefinition.Name == null)
                throw new ArgumentNullException(nameof(tierDefinition.Name), "Property is required for class TierDefinition.");

            if (tierDefinition.DisplayName == null)
                throw new ArgumentNullException(nameof(tierDefinition.DisplayName), "Property is required for class TierDefinition.");

            if (tierDefinition.Features == null)
                throw new ArgumentNullException(nameof(tierDefinition.Features), "Property is required for class TierDefinition.");

            if (tierDefinition.PeriodOption.IsSet && tierDefinition.Period == null)
                throw new ArgumentNullException(nameof(tierDefinition.Period), "Property is required for class TierDefinition.");

            writer.WriteString("name", tierDefinition.Name);

            writer.WriteString("display_name", tierDefinition.DisplayName);

            writer.WriteNumber("price_eur_cents", tierDefinition.PriceEurCents);

            writer.WriteNumber("rate_limit_fast", tierDefinition.RateLimitFast);

            writer.WriteNumber("rate_limit_thorough", tierDefinition.RateLimitThorough);

            writer.WritePropertyName("features");
            JsonSerializer.Serialize(writer, tierDefinition.Features, jsonSerializerOptions);
            if (tierDefinition.PeriodOption.IsSet)
                writer.WriteString("period", tierDefinition.Period);
        }
    }
}
